### ISSUE TITLE
shim_eth_vlan, The Immortal: can't rmmod it.

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#753] opened 2015-09-23 07:03 UTC
Branch: pristine-1.3

Once modprobed and used in experiment is no more possible to remove(rmmod) it from the kernel, even if lsmod show it not in use by anyone.

**Comment by edugrasa** [comment] 2016-02-15 10:58
The issue is related to one qdisc not being destroyed. Fixing it..

**Comment by edugrasa** [comment] 2016-02-15 11:10
Fixed by #869

**Closed by edugrasa** 2016-02-15 11:10 UTC
Labels: bug
