### ISSUE TITLE
kernel bug when killing ipcm with a flow allocated

### ISSUE THREAD

**Issue by bernatgaston** [IRATI/stack#616] opened 2015-05-27 12:38 UTC
I have the manager and the MAD in one node with a local flow (normal dif) then I kill the ipcm and this happens. Note the gap between timestamps:
5653
and 
5670

At 5653 I trigered the kill signal, It gets locked some time and then it shows the bug and continues until stop.

[ 5652.706643] rina-rtimer(DBG): Previously inactive Timer f2deeac0 restarted (function = f904f010, data = f2dee1c0, expires = 1387264 (195900)
[ 5652.713011] rina-kfa(DBG): Finishing (write)
[ 5652.715585] rina-syscalls(DBG): Exiting SYSC_sdu_write syscall body
[ 5652.721250] rina-syscalls(DBG): Entered SYSC_sdu_read syscall body
[ 5652.725469] rina-syscalls(DBG): Handling personality hook sdu_read
[ 5652.729078] rina-syscalls(DBG): Calling personality hook sdu_read
[ 5652.732541] rina-personality-default(DBG): Calling wrapped function
[ 5652.735913] rina-kfa(DBG): Trying to read SDU from port-id 2
[ 5652.739149] rina-rqueue(DBG): Entry f569c920 head-popped from queue f0497c30 (length = 0)
[ 5652.743117] rina-kfa(DBG): Finishing (read)
[ 5652.746582] rina-syscalls(DBG): Personality returned value 0
[ 5652.750595] rina-syscalls(DBG): Exiting SYSC_sdu_read syscall body
[ 5653.264101] rina-dt-utils(DBG): RTX timer triggered...
[ 5653.270868] rina-dt-utils(DBG): RTXQ f0d1fbd8 has delivered until 0
[ 5653.278128] rina-dt-utils(DBG): RTX timer ending...
[ 5653.344051] rina-dt-utils(DBG): RTX timer triggered...
[ 5653.350559] rina-dt-utils(DBG): RTXQ f0d1fbc8 has delivered until 0
[ 5653.357642] rina-dt-utils(DBG): RTX timer ending...
[ 5670.423091] rina-syscalls(DBG): Entered SYSC_deallocate_port syscall body
[ 5670.431831] rina-syscalls(DBG): Entered SYSC_deallocate_port syscall body
[ 5670.431833] rina-syscalls(DBG): Handling personality hook deallocate_port
[ 5670.431834] rina-syscalls(DBG): Calling personality hook deallocate_port
[ 5670.431836] rina-personality-default(DBG): Calling wrapped function
[ 5670.431839] rina-efcp(DBG): EFCP connection destroy called
[ 5670.431844] rina-kfa(DBG): Destroying kfa flow now...
[ 5670.431845] rina-kfa(DBG): We are destroying flow 2
[ 5670.431848] rina-rfifo(DBG): FIFO f0d1f970 destroyed successfully
[ 5670.431850] rina-pidm(DBG): Bitmap release completed successfully (port_id: 2)
[ 5670.431853] rina-rtimer(DBG): Timer f2dee380 is not pending, can't stop it
[ 5670.431854] rina-rtimer(DBG): Timer f2dee380 destroyed
[ 5670.431856] rina-rtimer(DBG): Timer f2deeac0 stopped
[ 5670.431857] rina-rtimer(DBG): Timer f2deeac0 destroyed
[ 5670.431858] rina-rtimer(DBG): Timer f2dee040 stopped
[ 5670.431859] rina-rtimer(DBG): Timer f2dee040 destroyed
[ 5670.431861] BUG: sleeping function called from invalid context at kernel/locking/mutex.c:103
[ 5670.431863] in_atomic(): 1, irqs_disabled(): 1, pid: 4219, name: ipcp
[ 5670.431867] CPU: 0 PID: 4219 Comm: ipcp Not tainted 3.15.0 #27
[ 5670.431868] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[ 5670.431875]  00000000 00000000 c2123e84 c160512f 0000107b c2123ea4 c1068df7 c17d6ad8
[ 5670.431879]  00000001 00000001 0000107b c2114798 f2dee1d0 c2123eb4 c160dba4 f2dee1c8
[ 5670.431883]  f2dee1d0 c2123ec4 f905982d f2dee1c0 f0d1f430 c2123ed8 f904f786 f0288280
[ 5670.431884] Call Trace:
[ 5670.431897]  [<c160512f>] dump_stack+0x48/0x60
[ 5670.431904]  [<c1068df7>] __might_sleep+0xc7/0x100
[ 5670.431909]  [<c160dba4>] mutex_lock+0x24/0x48
[ 5670.431927]  [<f905982d>] rina_component_fini+0x1d/0x60 [rina_personality_default]
[ 5670.431938]  [<f904f786>] dtp_destroy+0x56/0x90 [rina_personality_default]
[ 5670.431949]  [<f9050a80>] efcp_destroy+0x70/0x110 [rina_personality_default]
[ 5670.431959]  [<f90513af>] efcp_connection_destroy+0x7f/0x130 [rina_personality_default]
[ 5670.431964]  [<c1092b25>] ? console_trylock+0x15/0x50
[ 5670.431968]  [<f814aac1>] remove_all_cepid.isra.0+0x31/0x70 [normal_ipcp]
[ 5670.431971]  [<f814b586>] normal_deallocate+0x76/0x110 [normal_ipcp]
[ 5670.431983]  [<f9058f6f>] kipcm_deallocate_port+0x2f/0x80 [rina_personality_default]
[ 5670.431993]  [<f905918d>] default_deallocate_port+0x4d/0x50 [rina_personality_default]
[ 5670.431999]  [<c15fa642>] SyS_deallocate_port+0xb2/0xd0
[ 5670.432005]  [<c161760c>] sysenter_do_call+0x12/0x22
[ 5670.432008] rina-dtp(DBG): Instance f2dee1c0 destroyed successfully
[ 5670.432018] rina-rtimer(DBG): Timer f008e5c0 is not pending, can't stop it
[ 5670.432019] rina-rtimer(DBG): Timer f008e5c0 destroyed
[ 5670.432022] rina-dtcp(DBG): Instance f008e0c0 destroyed successfully
[ 5670.432024] rina-dt(DBG): Instance f0288ba0 destroyed successfully
[ 5670.432025] rina-cidm(DBG): Bitmap release completed successfully
[ 5670.432033] rina-efcp(DBG): EFCP instance f0288280 finalized successfully
[ 5670.432064] rina-syscalls(DBG): Exiting SYSC_deallocate_port syscall body
[ 5670.636921] rina-syscalls(DBG): Handling personality hook deallocate_port
[ 5670.640789] rina-syscalls(DBG): Calling personality hook deallocate_port
[ 5670.644746] rina-personality-default(DBG): Calling wrapped function
[ 5670.648385] rina-efcp(DBG): EFCP connection destroy called
[ 5670.652379] rina-rwq(DBG): Work posted on workqueue f56bb780, please wait ...
[ 5670.652379] rina-rtimer(DBG): Timer f2dee000 is not pending, can't stop it
[ 5670.659682] rina-kfa(DBG): Waking up all!
[ 5670.659690] rina-kfa(DBG): Queue-ready check called
[ 5670.659690] rina-kfa(DBG): Queue-ready / flow state is PORT_STATE_DEALLOCATED
[ 5670.659691] rina-kfa(DBG): Read woken up (0)
[ 5670.659692] rina-kfa(DBG): Finishing (read)
[ 5670.659692] rina-kfa(DBG): We are destroying flow 1
[ 5670.659693] rina-rfifo(DBG): FIFO c2097de0 destroyed successfully
[ 5670.659694] rina-pidm(DBG): Bitmap release completed successfully (port_id:

**Comment by msune** [comment] 2015-06-30 10:11
Can this still be reproduced @bernatgaston ?

**Comment by edugrasa** [comment] 2015-10-20 13:21
Closing, not reproducible anymore (@bernatgaston cannot reproduce it as well)

**Closed by edugrasa** 2015-10-20 13:21 UTC
Labels: bug
