### ISSUE TITLE
CRC check fails when using normal over shim-eth-vlan

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#456] opened 2015-02-20 15:32 UTC
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Feb 10, 2015 at 16:05 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/453_

----

[  691.276083] rina-serdes(ERR): Bad CRC, PDU has been corrupted
[  691.276139] rina-rmt(ERR): Failed to deserialize PDU!
[  691.276193] rina-normal-ipc(ERR): Enqueue :Could not post SDU into the RMT
[  691.276253] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP ...

Happens since serdes uses the length it got from the shim-eth-vlan, but should only rely on the PCI in the PDU of the normal DIF.

**Comment by kewinrausch** [comment] 2015-02-20 15:32
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Tuesday Feb 10, 2015 at 16:10 GMT_

----

Imagine the PDU had been encrypted, if the shim provides more bytes (the padding) to the upper IPC Process, decryption won't work (and the PCI cannot be checked since you have to decrypt first).

I think that the issue is that the minimum PDU size for using she shim-eth-vlan is 42, and we should enforce this.

**Comment by kewinrausch** [comment] 2015-02-20 15:33
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Feb 10, 2015 at 16:20 GMT_

----

Yes, that would also fail. 

Well, yeah, probably we should enforce a minimum SDU size as well. But a normal IPC process should also just use its own PCI, and not rely on information from the DIF it is using.

**Comment by kewinrausch** [comment] 2015-02-20 15:33
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vmaffione](https://github.com/vmaffione)**
_Tuesday Feb 10, 2015 at 16:22 GMT_

----

It's not clear to me, however, whether we should enrcypt also the PDU header. Why not encrypting just the DU parts?

**Comment by kewinrausch** [comment] 2015-02-20 15:33
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Feb 10, 2015 at 16:25 GMT_

----

That's policy as far as I know. 

Ok, got what Eduard was saying now as well. Well, maybe you would not encrypt the PDU length.

**Comment by kewinrausch** [comment] 2015-02-20 15:33
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Tuesday Feb 10, 2015 at 16:26 GMT_

----

That's a policy. You may want to encrypt just the payload, just the PCI or both (together or separate). Y

You encrypt the PDU header if you don't trust the N-1 DIF (remember that SDU Protection is for protecting the DIF-generated data mainly, each DIF/DAF should protect its own data).

You cannot force this  (not encrypting the PDU length), sending fields on the clear is providing hints to the N-1 DIF, and if you don't trust it, well, you don't trust it :)

**Comment by kewinrausch** [comment] 2015-02-20 15:33
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Feb 10, 2015 at 16:29 GMT_

----

Yeah, also policy I guess. But the main point is that the shims (in our implementation) have to at least try to report the correct length :) 

And enforcing a minimum SDU size may not be a bad idea to add soon, since we had the same problem appear elsewhere as well. Padding can be added by the IPC process using the DIF with a min size.

**Comment by edugrasa** [comment] 2016-02-09 16:38
@sandervrijders has this been addressed? What do we need to do to fix it?

**Comment by edugrasa** [comment] 2016-02-10 15:53
Closing, duplicate of #417

**Closed by edugrasa** 2016-02-10 15:53 UTC
Labels: bug, imported
