### ISSUE TITLE
configuration of ipcm manager file in ubuntu 16.04

### ISSUE THREAD

**Issue by samsneelam1981** [IRATI/stack#1278] opened 2019-03-07 07:39 UTC

**Comment by samsneelam1981** [comment] 2019-03-07 07:41
I'm getting confused how to configure the ipcm manager file before starting tutorials in ubuntu 16.04. can any one help regarding this

**Comment by samsneelam1981** [comment] 2019-03-07 07:45
unable to open ipcm console after running ipcm.conf in ubuntu 16.04

**Comment by edugrasa** [comment] 2019-03-11 14:09
Hi,

Which tutorial are you trying to follow, the first one? https://github.com/IRATI/stack/wiki/Tutorial-1:-DIF-over-a-VLAN-(point-to-point-DIF)

IPC Manager configuration files are already included. Which path did you install IRATI on?

**Comment by samsneelam1981** [comment] 2019-03-12 09:22
i installed on /usr/local/irati 
I was able to install it successfully on Debian 8. But when I am trying Tutorial 1: After some statements saying that are similar to signals like SIGSEGV are successfully opened - no console is getting opened.  the cursor remains still ..

**Comment by edugrasa** [comment] 2019-03-13 10:51
Hi, 

Could you post some logs reporting the problems you are describing? Otherwise it's hard to figure out :) Thanks!

**Comment by samsneelam1981** [comment] 2019-03-13 12:44
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest fare.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest default.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest sm-cbac.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest sm-auth-psoc.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest sm-example.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest rina-default-plugin.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest sm-passwd.manifest
3490(1552521147)#ipcm-catalog (INFO): Catalog: found manifest nsm-address-change.manifest
3490(1552521147)#ipcm-catalog (WARN): Failed to open plugins directory: '/lib/modules/4.1.33-irati/extra'
3490(1552521147)#ipcm.dif-allocator (ERR): Unrecognized DIF Allocator type: , using default
3490(1552521147)#ipcm.dif-allocator (INFO): DIF Directory file: ../etc/da.map
3490(1552521147)#rinad.rina-configuration (WARN): Cannot open apps to DIF mappings file
3490(1552521147)#ipcm.dif-template-manager (INFO): Template folder: ../etc
3490(1552521147)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
3490(1552521147)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shimeth.system1.100.dif
3490(1552521147)#ipcm (INFO)[create_ipcp]: IPC process eth.1.IPCP:1:: created and waiting for initialization[id = 1]

3490(1552521147)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 1] created

3490(1552521147)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process eth.1.IPCP:1:: to DIF 100:::

3490(1552521147)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process eth.1.IPCP:1:: [success=0]

3490(1552521147)#ipcm (ERR)[apply_configuration]: Problems assigning IPCP 1 to DIF 100

3490(1552521147)#ipcm (INFO)[create_ipcp]: IPC process Normal.1.IPCP:1:: created and waiting for initialization[id = 2]

3490(1552521147)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 2] created

3490(1552521147)#ipcm.ipcp (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

3490(1552521147)#ipcm-catalog (INFO): Plugin 'rina-default-plugin' successfully loaded
3490(1552521147)#ipcm (INFO)[plugin_load]: Issued plugin-load to IPC process Normal.1.IPCP:1::

3490(1552521147)#ipcm.policies (INFO)[ipc_process_plugin_load_response_handler]: plugin-load-op [plugin=default, load=1] completed on IPC process Normal.1.IPCP:1:: [success=1]

3490(1552521147)#ipcm-catalog (INFO): Plugin 'default' successfully loaded
3490(1552521147)#ipcm-catalog (WARN): Catalog does not contain a policy-set called default for component errc
3490(1552521147)#ipcm-catalog (WARN): Failed to load policy-set errc/default
3490(1552521147)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process Normal.1.IPCP:1:: to DIF Normal.DIF:::

3490(1552521147)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process Normal.1.IPCP:1:: [success=1]

3490(1552521147)#ipcm (ERR)[register_at_dif]: : Error while requesting registration: Error: the IPC Process is not member of a DIF

3490(1552521147)#ipcm (ERR)[apply_configuration]: Problems registering IPCP 2 to DIF 100

**Comment by samsneelam1981** [comment] 2019-03-13 12:45
Thanks for help

**Comment by samsneelam1981** [comment] 2019-03-13 13:12
This is from Normal.1.IPCP-1.log

3496(1552521147)#ipcp[2].ipc-process (INFO): Librina initialized
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATION_FAILED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_DECLARED_DEAD
3496(1552521147)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
3496(1552521147)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_ALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_DEALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event IPCP_INTERNAL_FLOW_ALLOCATION_FAILED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
3496(1552521147)#internal-events (INFO): EventListener subscribed to event CONNECTIVITY_TO_NEIGHBOR_LOST
3496(1552521147)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
3496(1552521147)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
3496(1552521147)#ipcp[2].normal-ipcp (INFO): Initialized IPC Process with name: Normal.1.IPCP, instance 1, id 2 
3496(1552521147)#ipcp[2] (INFO): IPC Process name:     Normal.1.IPCP
3496(1552521147)#ipcp[2] (INFO): IPC Process instance: 1
3496(1552521147)#ipcp[2] (INFO): IPC Process id:       2
3496(1552521147)#ipcp[2] (INFO): IPC Manager port:     1
3496(1552521147)#ipcp[2] (INFO): IPC Process type:     normal-ipc
3496(1552521147)#ipcp[2] (INFO): IPC Process initialized, executing event loop...
3496(1552521147)#librina.application (INFO): Plugin default loaded successfully
3496(1552521147)#librina.application (INFO): Pluggable component 'security-manager/default' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'security-manager/PSOC_authentication-none' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'flow-allocator/default' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'flow-allocator/RoundRobin' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'flow-allocator/qta-ps' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'namespace-manager/default' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'resource-allocator/default' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'enrollment-task/default' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'routing/link-state' [default] published
3496(1552521147)#librina.application (INFO): Pluggable component 'routing/static' [default] published
3496(1552521147)#ipcp (INFO): PDUFT Generator policy-set default added to the resource-allocator
3496(1552521147)#librina.application (INFO): Policy-set link-state selected for component routing
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_DEALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event N_MINUS_1_FLOW_ALLOCATED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_ADDED
3496(1552521147)#internal-events (INFO): EventListener subscribed to event CONNECTIVITY_TO_NEIGHBOR_LOST
3496(1552521147)#internal-events (INFO): EventListener subscribed to event ADDRESS_CHANGE
3496(1552521147)#internal-events (INFO): EventListener subscribed to event NEIGHBOR_ADDRESS_CHANGE
3496(1552521147)#librina.application (INFO): Policy-set default selected for component namespace-manager
3496(1552521147)#librina.application (INFO): Policy-set default selected for component security-manager
3496(1552521147)#librina.security-manager (INFO): Authentication policy-set PSOC_authentication-none added to the security-manager
3496(1552521147)#librina.application (INFO): Policy-set default selected for component flow-allocator
3496(1552521147)#librina.application (INFO): Policy-set default selected for component enrollment-task
3496(1552521147)#ipcp[2].enrollment-task (INFO): Could not parse use_reliable_n_flow, using default value: 0

**Comment by samsneelam1981** [comment] 2019-03-13 13:15
Pls help me what to do run the tutorials successfully. My OS is Ubuntu 16.04

**Comment by edugrasa** [comment] 2019-03-13 13:37
See the error there..

    3490(1552521147)#ipcm (ERR)[apply_configuration]: Problems assigning IPCP 1 to DIF 100

Did you actually create the VLAN 100 in the interface? See the step
https://github.com/IRATI/stack/wiki/Tutorial-1:-DIF-over-a-VLAN-(point-to-point-DIF)#configuring-the-vlan

Otherwise the system should be ok and should be able to connect to the IPCM console. Make sure you run the socat command as root though (or use sudo)

    sudo socat - UNIX:/usr/local/irati/var/run/ipcm-console.sock

**Comment by samsneelam1981** [comment] 2019-03-14 05:55
Did the following after your suggestion, I am posting the following which I got from the terminal when executed - 
root@nitm02:/usr/local/irati/bin# ./ipcm -c ../etc/ipcm.conf 
1949(1552582884)#ipcm (DBG): SIGSEGV handler installed successfully
1949(1552582884)#ipcm (DBG): SIGINT handler installed successfully
1949(1552582884)#ipcm (DBG): SIGQUIT handler installed successfully
1949(1552582884)#ipcm (DBG): SIGTERM handler installed successfully
1949(1552582884)#ipcm (DBG): SIGHUP handler installed successfully
1949(1552582884)#ipcm (DBG): SIGPIPE handler installed successfully
1949(1552582884)#ipcm (DBG): SIGCHLD handler installed successfully
1949(1552582884)#ipcm (DBG): Config file is: ../etc/ipcm.conf
1949(1552582884)#librina.timer (DBG): Timer with ID 11103920 started
1949(1552582884)#librina.logs (DBG): New log level: INFO
1958(1552582884)#ipcp[2] (DBG): SIGSEGV handler installed successfully
1958(1552582884)#ipcp[2] (DBG): SIGPIPE handler installed successfully
1958(1552582884)#ipcp[2] (DBG): SIGINT handler installed successfully
1958(1552582884)#librina.logs (DBG): New log level: INFO
----
In another terminal 

root@nitm02:/usr/local/irati/bin# socat - UNIX:/usr/local/irati/var/run/ipcm-console.sock
IPCM >>> list-ipcps
Management Agent not started

Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | eth.1.IPCP:1:: | shim-eth-vlan | INITIALIZED | - | -
    2 | Normal.1.IPCP:1:: | normal-ipc | ASSIGNED TO DIF Normal.DIF | - | -

IPCM >>> enroll-to-dif 2 normal.DIF 100
Enrollment operation failed

-- 
The Log file is as follows
1949(1552582884)#ipcm-catalog (INFO): Catalog: found manifest sm-example.manifest
1949(1552582884)#ipcm-catalog (INFO): Catalog: found manifest rina-default-plugin.manifest
1949(1552582884)#ipcm-catalog (INFO): Catalog: found manifest sm-passwd.manifest
1949(1552582884)#ipcm-catalog (INFO): Catalog: found manifest nsm-address-change.manifest
1949(1552582884)#ipcm-catalog (WARN): Failed to open plugins directory: '/lib/modules/4.1.33-irati/extra'
1949(1552582884)#ipcm.dif-allocator (ERR): Unrecognized DIF Allocator type: , using default
1949(1552582884)#ipcm.dif-allocator (INFO): DIF Directory file: ../etc/da.map
1949(1552582884)#rinad.rina-configuration (WARN): Cannot open apps to DIF mappings file
1949(1552582884)#ipcm.dif-template-manager (INFO): Template folder: ../etc
1949(1552582884)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
1949(1552582884)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shimeth.system1.100.dif
1949(1552582884)#ipcm (INFO)[create_ipcp]: IPC process eth.1.IPCP:1:: created and waiting for initialization[id = 1]

1949(1552582884)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 1] created

1949(1552582884)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process eth.1.IPCP:1:: to DIF 100:::

1949(1552582884)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process eth.1.IPCP:1:: [success=0]

1949(1552582884)#ipcm (ERR)[apply_configuration]: Problems assigning IPCP 1 to DIF 100

1949(1552582884)#ipcm (INFO)[create_ipcp]: IPC process Normal.1.IPCP:1:: created and waiting for initialization[id = 2]

1949(1552582884)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 2] created

1949(1552582884)#ipcm.ipcp (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

1949(1552582884)#ipcm-catalog (INFO): Plugin 'rina-default-plugin' successfully loaded
1949(1552582884)#ipcm (INFO)[plugin_load]: Issued plugin-load to IPC process Normal.1.IPCP:1::

1949(1552582884)#ipcm.policies (INFO)[ipc_process_plugin_load_response_handler]: plugin-load-op [plugin=default, load=1] completed on IPC process Normal.1.IPCP:1:: [success=1]

1949(1552582884)#ipcm-catalog (INFO): Plugin 'default' successfully loaded
1949(1552582884)#ipcm-catalog (WARN): Catalog does not contain a policy-set called default for component errc
1949(1552582884)#ipcm-catalog (WARN): Failed to load policy-set errc/default
1949(1552582884)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process Normal.1.IPCP:1:: to DIF Normal.DIF:::

1949(1552582884)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process Normal.1.IPCP:1:: [success=1]

1949(1552582884)#ipcm (ERR)[register_at_dif]: : Error while requesting registration: Error: the IPC Process is not member of a DIF

1949(1552582884)#ipcm (ERR)[apply_configuration]: Problems registering IPCP 2 to DIF 100

1949(1552582934)#ipcm (INFO)[enroll_to_dif]: Requested enrollment of IPC process Normal.1.IPCP:1:: to DIF normal.DIF::: through DIF 100::: and neighbor IPC process :::

1949(1552582934)#ipcm.ipcp (ERR)[enroll_to_dif_response_event_handler]: : Error: Enrollment operation of process Normal.1.IPCP:1:: failed
---
Results from ifconfig
root@nitm02:/usr/local/irati/bin# ifconfig 
eno1      Link encap:Ethernet  HWaddr 18:66:da:14:53:a2  
          inet addr:192.168.0.4  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::dd8e:5366:34aa:2d05/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2908 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2207 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1954671 (1.9 MB)  TX bytes:334812 (334.8 KB)
          Interrupt:20 Memory:f7c00000-f7c20000 

eth1.100  Link encap:Ethernet  HWaddr 18:66:da:14:53:a2  
          inet6 addr: fe80::1a66:daff:fe14:53a2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:5018 (5.0 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6691 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6691 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:502104 (502.1 KB)  TX bytes:502104 (502.1 KB)
---
Pls help in the further step

**Comment by edugrasa** [comment] 2019-03-14 07:43
Ok, the problem is that the interfaces in your system are not called ethX but enoX. So

1) You have to create the VLAN on eno1, not eth1

    ip link add link eno1 name eth1.100 type vlan id 100
    ip link set dev eno1 up
    ip link set dev eno1.100 up

2) In the shim DIF configuration file (/usr/local/irati/etc/shimeth.system1.100.dif), you have to use eno1 as the interface name

    {
        "configParameters": {
            "interface-name": "eno1"
         },
        "difType": "shim-eth-vlan"
    }

**Comment by edugrasa** [comment] 2019-03-14 10:28
We've improved :) Now this system (machine) is ok, see that the shim Ethernet IPC Process is now assigned to DIF 100 (which was not before)

````
    Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | eth.1.IPCP:1:: | shim-eth-vlan | ASSIGNED TO DIF 100 | Normal.1.IPCP-1-- | -
    2 | Normal.1.IPCP:1:: | normal-ipc | ASSIGNED TO DIF Normal.DIF | - | -
````

Enrolment still does not work, but this requires 2 systems (machines). Have you checked your second machine, to make sure it does not have the same issues with the interface name as the first one?

**Comment by samsneelam1981** [comment] 2019-03-14 10:56
yes, I connected 2 systems through a router. And this is the report from its log file **[From System 2]**
---
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest sm-example.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest sm-auth-psoc.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest sm-cbac.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest rina-default-plugin.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest nsm-address-change.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest sm-passwd.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest default.manifest
2234(1552599847)#ipcm-catalog (INFO): Catalog: found manifest fare.manifest
2234(1552599847)#ipcm-catalog (WARN): Failed to open plugins directory: '/lib/modules/4.1.33-irati/extra'
2234(1552599847)#ipcm.dif-allocator (ERR): Unrecognized DIF Allocator type: , using default
2234(1552599847)#ipcm.dif-allocator (INFO): DIF Directory file: ../etc/da.map
2234(1552599847)#rinad.rina-configuration (WARN): Cannot open apps to DIF mappings file
2234(1552599847)#ipcm.dif-template-manager (INFO): Template folder: ../etc
2234(1552599847)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
2234(1552599847)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: shimeth.system2.100.dif
2234(1552599847)#ipcm (INFO)[create_ipcp]: IPC process eth.1.IPCP:1:: created and waiting for initialization[id = 1]

2234(1552599847)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 1] created

2234(1552599847)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process eth.1.IPCP:1:: to DIF 100:::

2234(1552599847)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process eth.1.IPCP:1:: [success=1]

2234(1552599847)#ipcm (INFO)[create_ipcp]: IPC process Normal.2.IPCP:1:: created and waiting for initialization[id = 2]

2234(1552599847)#ipcm.ipcp (INFO)[ipc_process_create_response_event_handler]: IPC process kernel components of [id = 2] created

2234(1552599847)#ipcm.ipcp (INFO)[ipc_process_daemon_initialized_event_handler]: IPC process daemon initialized [id = 2]

2234(1552599847)#ipcm-catalog (INFO): Plugin 'rina-default-plugin' successfully loaded
2234(1552599847)#ipcm (INFO)[plugin_load]: Issued plugin-load to IPC process Normal.2.IPCP:1::

2234(1552599847)#ipcm.policies (INFO)[ipc_process_plugin_load_response_handler]: plugin-load-op [plugin=default, load=1] completed on IPC process Normal.2.IPCP:1:: [success=1]

2234(1552599847)#ipcm-catalog (INFO): Plugin 'default' successfully loaded
2234(1552599847)#ipcm-catalog (WARN): Catalog does not contain a policy-set called default for component errc
2234(1552599847)#ipcm-catalog (WARN): Failed to load policy-set errc/default
2234(1552599847)#ipcm (INFO)[assign_to_dif]: Requested DIF assignment of IPC process Normal.2.IPCP:1:: to DIF Normal.DIF:::

2234(1552599847)#ipcm.ipcp (INFO)[assign_to_dif_response_event_handler]: DIF assignment operation completed for IPC process Normal.2.IPCP:1:: [success=1]

2234(1552599847)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process Normal.2.IPCP:1:: at DIF 100::: through IPC process eth.1.IPCP:1::

2234(1552599847)#ipcm.ipcp (INFO)[ipcm_register_response_ipcp]: IPC process Normal.2.IPCP:1:: informed about its registration to N-1 DIF 100:::

2234(1552599974)#ipcm (INFO)[enroll_to_dif]: Requested enrollment of IPC process Normal.2.IPCP:1:: to DIF normal.DIF::: through DIF 100::: and neighbor IPC process :::

2234(1552599974)#ipcm.ipcp (ERR)[enroll_to_dif_response_event_handler]: : Error: Enrollment operation of process Normal.2.IPCP:1:: failed
--- This is from terminals - 
rinauser@nit01:~$ sudo su
[sudo] password for rinauser: 
root@nit01:/home/rinauser# socat - UNIX:/usr/local/irati/var/run/ipcm-console.sock
IPCM >>> list-ipcps
Management Agent not started

Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
    1 | eth.1.IPCP:1:: | shim-eth-vlan | ASSIGNED TO DIF 100 | Normal.2.IPCP-1-- | -
    2 | Normal.2.IPCP:1:: | normal-ipc | ASSIGNED TO DIF Normal.DIF | - | -

IPCM >>> enroll-to-dif 2 normal.DIF 100
Enrollment operation failed

IPCM >>> 
---- 

rinauser@nit01:~$ sudo su
[sudo] password for rinauser: 
root@nit01:/home/rinauser# ip link add link eno1 name eno1.100 type vlan id 100
root@nit01:/home/rinauser# ip link set dev eno1 up
root@nit01:/home/rinauser# ip link set dev eno1.100 up
root@nit01:/home/rinauser# cd /stack/
root@nit01:/stack# ./load-irati-modules 
root@nit01:/stack# cd /usr/local/irati/bin/
root@nit01:/usr/local/irati/bin# ./ipcm -c ../etc/ipcm.conf 
2234(1552599847)#ipcm (DBG): SIGSEGV handler installed successfully
2234(1552599847)#ipcm (DBG): SIGINT handler installed successfully
2234(1552599847)#ipcm (DBG): SIGQUIT handler installed successfully
2234(1552599847)#ipcm (DBG): SIGTERM handler installed successfully
2234(1552599847)#ipcm (DBG): SIGHUP handler installed successfully
2234(1552599847)#ipcm (DBG): SIGPIPE handler installed successfully
2234(1552599847)#ipcm (DBG): SIGCHLD handler installed successfully
2234(1552599847)#ipcm (DBG): Config file is: ../etc/ipcm.conf
2234(1552599847)#librina.timer (DBG): Timer with ID 16539312 started
2234(1552599847)#librina.logs (DBG): New log level: INFO
2240(1552599847)#ipcp[2] (DBG): SIGSEGV handler installed successfully
2240(1552599847)#ipcp[2] (DBG): SIGPIPE handler installed successfully
2240(1552599847)#ipcp[2] (DBG): SIGINT handler installed successfully
2240(1552599847)#librina.logs (DBG): New log level: INFO

**--- From ifconfig ---**
rinauser@nit01:~$ ifconfig
eno1      Link encap:Ethernet  HWaddr 18:66:da:14:49:a6  
          inet addr:192.168.0.2  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::61a0:6ac3:8c67:cb01/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10780 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6339 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:8068116 (8.0 MB)  TX bytes:796763 (796.7 KB)
          Interrupt:20 Memory:f7c00000-f7c20000 

eno1.100  Link encap:Ethernet  HWaddr 18:66:da:14:49:a6  
          inet6 addr: fe80::1a66:daff:fe14:49a6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:4193 (4.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:942 errors:0 dropped:0 overruns:0 frame:0
          TX packets:942 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:80180 (80.1 KB)  TX bytes:80180 (80.1 KB)

rinauser@nit01:~$

---- 
These are all from the system-2  
Please tell me how to establish connection (tutorial -1). Thanks for your help

**Comment by edugrasa** [comment] 2019-03-14 11:03
Ok, so you connected the two systems through a router, maybe VLAN 100 is not configured in the router? You can just try to connect the two systems directly through a cable and see if it works; if so the problem is definitely the router (and probably related to the VLAN 100).

**Comment by samsneelam1981** [comment] 2019-03-14 12:00
Wow.  Thank you. It worked...  Now moving into tutorial 2..

**Comment by edugrasa** [comment] 2019-03-14 12:03
Cool, closing this issue :)

**Closed by edugrasa** 2019-03-14 12:03 UTC
