### ISSUE TITLE
SHIM TCP cleaning

### ISSUE THREAD

**Issue by bernatgaston** [IRATI/stack#575] opened 2015-05-08 13:17 UTC
When destroying a shim tcp-udp ipcp, it does not unregister applications and sockets are not closed. When you try to run again and register one applications it fails

May  8 17:12:22 irati-vm kernel: [ 1781.787280] rina-pidm(DBG): Bitmap allocation completed successfully (id = 74)
May  8 17:12:22 irati-vm kernel: [ 1781.798632] rina-rmem(DBG): generic_alloc(16) = dfe0a9b0
May  8 17:12:22 irati-vm kernel: [ 1781.804757] rina-shim-tcp-udp(DBG): I'm in tcp_udp_flow_allocate_request (net/rina/ipcps/shim-tcp-udp.c:498)
May  8 17:12:22 irati-vm kernel: [ 1781.811719] rina-shim-tcp-udp(DBG): I'm in find_flow_by_port (net/rina/ipcps/shim-tcp-udp.c:245)
May  8 17:12:22 irati-vm kernel: [ 1781.816732] rina-rmem(DBG): generic_alloc(64) = f605cb00
May  8 17:12:22 irati-vm kernel: [ 1781.820563] rina-shim-tcp-udp(DBG): Allocate request flow added
May  8 17:12:22 irati-vm kernel: [ 1781.824197] rina-ipcp-utils(DBG): No flags, name comparison will be meaningless ...
May  8 17:12:22 irati-vm kernel: [ 1781.828882] rina-shim-tcp-udp(DBG): Directory entry found
May  8 17:12:22 irati-vm kernel: [ 1781.832211] rina-shim-tcp-udp(DBG): Max allowable gap is 0
May  8 17:12:22 irati-vm kernel: [ 1781.835798] rina-shim-tcp-udp(DBG): Reliable flow requested
May  8 17:12:22 irati-vm kernel: [ 1781.839855] rina-shim-tcp-udp(ERR): Could not connect TCP socket
May  8 17:12:22 irati-vm kernel: [ 1781.844965] rina-shim-tcp-udp(DBG): I'm in unbind_and_destroy_flow (net/rina/ipcps/shim-tcp-udp.c:405)

**Comment by sandervrijders** [comment] 2015-05-08 14:09
I think this issue is very similar to #554. Before the distributed loop the KFA cleaned up flows AFAIK.

**Comment by edugrasa** [comment] 2015-05-10 21:45
But the problem is not related to cleaning up flows (which also won't happen, so must be added as well), but about unregistering applications and closing the sockets related to these registered applications. This code should be in tcp_udp_destroy (the factory). As other IPCPs, when the shim TCP UDP IPCP is destroyed it has to:

* Destroy all active flows and free any OS resources associated to them.
* Unregister all active applications and free any OS resources associated to them.

It's not urgent, but it's inconvenient since Ctrl-C on the IPCM doesn't clean up the sockets used by the shim, therefore when you restart again the registration doesn't work.

**Comment by edugrasa** [comment] 2016-02-15 10:57
Fixed by #868

**Closed by edugrasa** 2016-02-15 10:57 UTC
Labels: problem
