### ISSUE TITLE
Running IRATI on a VirtualBox machine with less than 1GB RAM

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#784] opened 2015-11-03 12:39 UTC
**What:**
This happens to me every time I try to run IRATI stack on an Oracle VirtualBox Virtual Machine with less than 1 GB of RAM. I'm aware of this problem from January 2015, but higher priority issues make me forgot about it. :scream:

**Where:**
For the moment the problem afflict me on Pristine-1.3 branch. 

The following trace was taken thanks to the serial console. 
The VM had 512 MB of RAM.

```
[   31.016607] Kernel panic - not syncing: Out of memory and no killable processes...
[   31.016607] 
[   31.280944] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 3.15.0 #38
[   31.468271] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[   31.599345]  ffff880015b3b968 ffffffff81511900 ffffffff81721758 ffffffff815105e3
[   31.791722]  0000000000000008 ffff880015b3b978 ffff880015b3b910 ffffffff81510b18
[   32.015769]  0000000000000000 0000000000000000 000000000000095e 0000000000000092
[   32.211297] Call Trace:
[   32.296479]  [<ffffffff81511900>] ? dump_stack+0x41/0x51
[   32.448795]  [<ffffffff815105e3>] ? panic+0xc6/0x1ea
[   32.588839]  [<ffffffff81510b18>] ? dump_header+0x109/0x1fd
[   32.723553]  [<ffffffff8113854e>] ? out_of_memory+0x4ee/0x4f0
[   32.724682]  [<ffffffff8113e997>] ? __alloc_pages_nodemask+0xb27/0xb70
[   32.730044]  [<ffffffff8117cc14>] ? alloc_page_interleave+0x44/0xa0
[   32.741862]  [<ffffffff8117cf44>] ? alloc_pages_current+0xf4/0x160
[   32.857482]  [<ffffffff811341a9>] ? find_get_entry+0x19/0xb0
[   32.895812]  [<ffffffff81135521>] ? grab_cache_page_write_begin+0x71/0xd0
[   32.903216]  [<ffffffff811c7263>] ? simple_write_begin+0x23/0x180
[   32.977147]  [<ffffffff81134410>] ? generic_perform_write+0xc0/0x1e0
[   32.977993]  [<ffffffff811bb4a2>] ? file_update_time+0x42/0xd0
[   32.978955]  [<ffffffff811364d7>] ? __generic_file_aio_write+0x227/0x3e0
[   32.980009]  [<ffffffff811366da>] ? generic_file_aio_write+0x4a/0xc0
[   32.981028]  [<ffffffff81947b3c>] ? bunzip2+0x3d9/0x3d9
[   32.981919]  [<ffffffff811a001c>] ? do_sync_write+0x5c/0x90
[   32.982854]  [<ffffffff811a0785>] ? vfs_write+0xb5/0x1d0
[   32.983767]  [<ffffffff81947b3c>] ? bunzip2+0x3d9/0x3d9
[   32.984951]  [<ffffffff811a1282>] ? SyS_write+0x42/0xa0
[   32.987084]  [<ffffffff81914897>] ? do_copy+0x6e/0x89
[   32.987956]  [<ffffffff81914666>] ? write_buffer+0x1d/0x2b
[   32.988907]  [<ffffffff81914697>] ? flush_buffer+0x23/0x7a
[   32.991118]  [<ffffffff81914674>] ? write_buffer+0x2b/0x2b
[   32.992211]  [<ffffffff81947db1>] ? gunzip+0x271/0x315
[   32.994596]  [<ffffffff81947b40>] ? nofill+0x4/0x4
[   32.995441]  [<ffffffff81914d6e>] ? unpack_to_rootfs+0x16a/0x288
[   32.996426]  [<ffffffff819145de>] ? initrd_load+0x3a/0x3a
[   32.997337]  [<ffffffff81914f85>] ? maybe_link.part.3+0xf9/0xf9
[   32.998313]  [<ffffffff81914fde>] ? populate_rootfs+0x59/0x10c
[   32.999279]  [<ffffffff81002162>] ? do_one_initcall+0xf2/0x1b0
[   33.000243]  [<ffffffff81082de8>] ? parse_args+0x248/0x4a0
[   33.001161]  [<ffffffff81913f9f>] ? kernel_init_freeable+0x186/0x207
[   33.002177]  [<ffffffff81505f70>] ? rest_init+0x80/0x80
[   33.003074]  [<ffffffff81505f7a>] ? kernel_init+0xa/0xf0
[   33.003977]  [<ffffffff8151fd3c>] ? ret_from_fork+0x7c/0xb0
[   33.004916]  [<ffffffff81505f70>] ? rest_init+0x80/0x80
[   33.013600] ---[ end Kernel panic - not syncing: Out of memory and no killable processes...
[   33.013600] 
```

**Comment by edugrasa** [comment] 2016-02-11 09:07
So apparently there is not enough memory in the kernel. We need to improve our memory management, fix memleaks, etc... @kewinrausch  since this issue is not reporting a specific problem to be fixed, can we close it?

**Comment by kewinrausch** [comment] 2016-02-11 09:21
@edugrasa: yeah, but don't forget about it. ;)

**Comment by edugrasa** [comment] 2016-02-11 09:23
Ok, this should be a KPI for the end of the project maybe ;) Be able to run the stack in 512 MB machines
BTW, not now, but when you have time, can you try again with current pristine-1.4?

Let's keep this issue open and you can report the results here then.

**Comment by kewinrausch** [comment] 2016-02-11 09:33
Yeah, for sure. 
Next week vWall is down and so it'll probably have to use VMs again.

**Comment by kewinrausch** [comment] 2016-02-16 09:18
Ok, I just tried with a 512 Mb RAM Virtual Box machine (64bit, 2 CPUs), and the problem persist. 
This happens even before the system spawn a console to log in, so somewhere during kernel initialization.

```
[   30.651819] Kernel panic - not syncing: Out of memory and no killable processes...
[   30.651819] 
[   30.936458] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.1.16 #2
[   31.126540] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[   31.392736]  0000000000000000 00000000000153c9 ffffffff8158b883 ffffffff8172eeb8
[   31.628807]  ffffffff8158a54e ffff88001ffedb28 0000000000000008 ffff880015e1b868
[   31.880682]  ffff880015e1b808 ffffffff818664e0 0000000000000000 0000000000000000
[   32.117426] Call Trace:
[   32.199352]  [<ffffffff8158b883>] ? dump_stack+0x40/0x50
[   32.367511]  [<ffffffff8158a54e>] ? panic+0xca/0x1fb
[   32.526639]  [<ffffffff8115b9bd>] ? __out_of_memory+0x53d/0x540
[   32.697786]  [<ffffffff8115bb53>] ? out_of_memory+0x53/0x70
[   32.807853]  [<ffffffff811612d8>] ? __alloc_pages_nodemask+0x928/0xa70
[   32.939982]  [<ffffffff811a2015>] ? interleave_nodes+0x75/0x90
[   33.057002]  [<ffffffff811a22c4>] ? alloc_page_interleave+0x44/0xa0
[   33.192659]  [<ffffffff811a2854>] ? alloc_pages_current+0xe4/0x110
[   33.324229]  [<ffffffff812dce00>] ? radix_tree_lookup_slot+0x10/0x30
[   33.459857]  [<ffffffff811586b8>] ? pagecache_get_page+0xf8/0x1a0
[   33.603941]  [<ffffffff811f026f>] ? inode_to_bdi+0x1f/0x60
[   33.721004]  [<ffffffff81158782>] ? grab_cache_page_write_begin+0x22/0x40
[   33.856880]  [<ffffffff811ee643>] ? simple_write_begin+0x23/0x170
[   33.988981]  [<ffffffff811577d3>] ? generic_perform_write+0xc3/0x1c0
[   34.093512]  [<ffffffff811e1fca>] ? file_update_time+0x3a/0xf0
[   34.193079]  [<ffffffff811597b8>] ? __generic_file_write_iter+0x168/0x1b0
[   34.334196]  [<ffffffff811598e1>] ? generic_file_write_iter+0xe1/0x1f0
[   34.474024]  [<ffffffff8195e4d2>] ? bunzip2+0x3ee/0x3ee
[   34.595449]  [<ffffffff811c6532>] ? __vfs_write+0xb2/0xf0
[   34.720460]  [<ffffffff811c6ba4>] ? vfs_write+0xa4/0x1b0
[   34.847604]  [<ffffffff8195e4d2>] ? bunzip2+0x3ee/0x3ee
[   34.958112]  [<ffffffff811c7912>] ? SyS_write+0x42/0xb0
[   35.058218]  [<ffffffff81927991>] ? xwrite+0x26/0x5a
[   35.152241]  [<ffffffff81927a4b>] ? do_copy+0x86/0xb3
[   35.236325]  [<ffffffff819277b7>] ? write_buffer+0x1f/0x2f
[   35.346884]  [<ffffffff819277ed>] ? flush_buffer+0x26/0x7f
[   35.466495]  [<ffffffff819277c7>] ? write_buffer+0x2f/0x2f
[   35.589596]  [<ffffffff8195e776>] ? __gunzip+0x29f/0x34b
[   35.698665]  [<ffffffff8195e822>] ? __gunzip+0x34b/0x34b
[   35.699830]  [<ffffffff8195e831>] ? gunzip+0xf/0x14
[   35.796200]  [<ffffffff8192772d>] ? initrd_load+0x3c/0x3c
[   35.912783]  [<ffffffff8195e822>] ? __gunzip+0x34b/0x34b
[   36.017158]  [<ffffffff81927f51>] ? unpack_to_rootfs+0x174/0x299
[   36.058805]  [<ffffffff8192772d>] ? initrd_load+0x3c/0x3c
[   36.060397]  [<ffffffff8195e822>] ? __gunzip+0x34b/0x34b
[   36.061483]  [<ffffffff81928177>] ? maybe_link.part.3+0x101/0x101
[   36.062688]  [<ffffffff819281d3>] ? populate_rootfs+0x5c/0x10f
[   36.103578]  [<ffffffff81002148>] ? do_one_initcall+0xd8/0x210
[   36.238957]  [<ffffffff8108d100>] ? parse_args+0x150/0x500
[   36.330179]  [<ffffffff819270f5>] ? kernel_init_freeable+0x18b/0x211
[   36.468454]  [<ffffffff81581750>] ? rest_init+0x80/0x80
[   36.578480]  [<ffffffff8158175e>] ? kernel_init+0xe/0xf0
[   36.689569]  [<ffffffff81591722>] ? ret_from_fork+0x42/0x70
[   36.815643]  [<ffffffff81581750>] ? rest_init+0x80/0x80
[   36.925843] ---[ end Kernel panic - not syncing: Out of memory and no killable processes...
[   36.925843] 
```

**Comment by vmaffione** [comment] 2016-02-16 09:20
It's funny because with QEMU I usually run the same stack with 256 MiB.

2016-02-16 10:18 GMT+01:00 Kewin Rausch <notifications@github.com>:

> Ok, I just tried with a 512 Mb RAM Virtual Box machine (64bit, 2 CPUs),
> and the problem persist.
> This happens even before the system spawn a console to log in, so
> somewhere during kernel initialization.
>
> [   30.651819] Kernel panic - not syncing: Out of memory and no killable processes...
> [   30.651819]
> [   30.936458] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.1.16 #2
> [   31.126540] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
> [   31.392736]  0000000000000000 00000000000153c9 ffffffff8158b883 ffffffff8172eeb8
> [   31.628807]  ffffffff8158a54e ffff88001ffedb28 0000000000000008 ffff880015e1b868
> [   31.880682]  ffff880015e1b808 ffffffff818664e0 0000000000000000 0000000000000000
> [   32.117426] Call Trace:
> [   32.199352]  [<ffffffff8158b883>] ? dump_stack+0x40/0x50
> [   32.367511]  [<ffffffff8158a54e>] ? panic+0xca/0x1fb
> [   32.526639]  [<ffffffff8115b9bd>] ? __out_of_memory+0x53d/0x540
> [   32.697786]  [<ffffffff8115bb53>] ? out_of_memory+0x53/0x70
> [   32.807853]  [<ffffffff811612d8>] ? __alloc_pages_nodemask+0x928/0xa70
> [   32.939982]  [<ffffffff811a2015>] ? interleave_nodes+0x75/0x90
> [   33.057002]  [<ffffffff811a22c4>] ? alloc_page_interleave+0x44/0xa0
> [   33.192659]  [<ffffffff811a2854>] ? alloc_pages_current+0xe4/0x110
> [   33.324229]  [<ffffffff812dce00>] ? radix_tree_lookup_slot+0x10/0x30
> [   33.459857]  [<ffffffff811586b8>] ? pagecache_get_page+0xf8/0x1a0
> [   33.603941]  [<ffffffff811f026f>] ? inode_to_bdi+0x1f/0x60
> [   33.721004]  [<ffffffff81158782>] ? grab_cache_page_write_begin+0x22/0x40
> [   33.856880]  [<ffffffff811ee643>] ? simple_write_begin+0x23/0x170
> [   33.988981]  [<ffffffff811577d3>] ? generic_perform_write+0xc3/0x1c0
> [   34.093512]  [<ffffffff811e1fca>] ? file_update_time+0x3a/0xf0
> [   34.193079]  [<ffffffff811597b8>] ? __generic_file_write_iter+0x168/0x1b0
> [   34.334196]  [<ffffffff811598e1>] ? generic_file_write_iter+0xe1/0x1f0
> [   34.474024]  [<ffffffff8195e4d2>] ? bunzip2+0x3ee/0x3ee
> [   34.595449]  [<ffffffff811c6532>] ? __vfs_write+0xb2/0xf0
> [   34.720460]  [<ffffffff811c6ba4>] ? vfs_write+0xa4/0x1b0
> [   34.847604]  [<ffffffff8195e4d2>] ? bunzip2+0x3ee/0x3ee
> [   34.958112]  [<ffffffff811c7912>] ? SyS_write+0x42/0xb0
> [   35.058218]  [<ffffffff81927991>] ? xwrite+0x26/0x5a
> [   35.152241]  [<ffffffff81927a4b>] ? do_copy+0x86/0xb3
> [   35.236325]  [<ffffffff819277b7>] ? write_buffer+0x1f/0x2f
> [   35.346884]  [<ffffffff819277ed>] ? flush_buffer+0x26/0x7f
> [   35.466495]  [<ffffffff819277c7>] ? write_buffer+0x2f/0x2f
> [   35.589596]  [<ffffffff8195e776>] ? __gunzip+0x29f/0x34b
> [   35.698665]  [<ffffffff8195e822>] ? __gunzip+0x34b/0x34b
> [   35.699830]  [<ffffffff8195e831>] ? gunzip+0xf/0x14
> [   35.796200]  [<ffffffff8192772d>] ? initrd_load+0x3c/0x3c
> [   35.912783]  [<ffffffff8195e822>] ? __gunzip+0x34b/0x34b
> [   36.017158]  [<ffffffff81927f51>] ? unpack_to_rootfs+0x174/0x299
> [   36.058805]  [<ffffffff8192772d>] ? initrd_load+0x3c/0x3c
> [   36.060397]  [<ffffffff8195e822>] ? __gunzip+0x34b/0x34b
> [   36.061483]  [<ffffffff81928177>] ? maybe_link.part.3+0x101/0x101
> [   36.062688]  [<ffffffff819281d3>] ? populate_rootfs+0x5c/0x10f
> [   36.103578]  [<ffffffff81002148>] ? do_one_initcall+0xd8/0x210
> [   36.238957]  [<ffffffff8108d100>] ? parse_args+0x150/0x500
> [   36.330179]  [<ffffffff819270f5>] ? kernel_init_freeable+0x18b/0x211
> [   36.468454]  [<ffffffff81581750>] ? rest_init+0x80/0x80
> [   36.578480]  [<ffffffff8158175e>] ? kernel_init+0xe/0xf0
> [   36.689569]  [<ffffffff81591722>] ? ret_from_fork+0x42/0x70
> [   36.815643]  [<ffffffff81581750>] ? rest_init+0x80/0x80
> [   36.925843] ---[ end Kernel panic - not syncing: Out of memory and no killable processes...
> [   36.925843]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/784#issuecomment-184592324>.
>



-- 
Vincenzo Maffione

**Comment by kewinrausch** [comment] 2016-02-16 09:27
Strange... so this could be something which depends on the emulator.
Can you try to run it on Virtual Box with the same setup I tried? Something like 512 Mb of RAM.

**Comment by sandervrijders** [comment] 2016-02-16 09:29
Yeah, and also, it is just a minimal part of the IRATI stack that gets loaded on boot. (The personality hooks)

**Comment by edugrasa** [comment] 2016-02-16 09:40
Reproduced the issue with XEN, but have more output. A real Linux person should check this (like @vmaffione). The problem doesn't seem to be the IRATI stack (it happens before loading it), but that the system run out of memory when "trying to unpack rootfs image as initramfs". 

```
[    0.852886] PCI: CLS 0 bytes, default 64
[    0.856190] Trying to unpack rootfs image as initramfs...
[    2.484480] swapper/0 invoked oom-killer: gfp_mask=0x200d2, order=0, oom_score_adj=0
[    2.490278] swapper/0 cpuset=/ mems_allowed=0
[    2.494345] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.1.16 #50
[    2.498483] Hardware name: Xen HVM domU, BIOS 4.4.1 06/11/2015
[    2.502550]  0000000000000000 ffff880014e4b6c8 ffffffff81782a79 00000000000016a4
[    2.509457]  0000000000000000 ffff880014e4b728 ffffffff81780f45 ffff880014e4b718
[    2.516371]  ffffffff810910e6 ffff88001f7f9b28 0000000000000000 00000000000200d2
[    2.523296] Call Trace:
[    2.525427]  [<ffffffff81782a79>] dump_stack+0x45/0x57
[    2.529081]  [<ffffffff81780f45>] dump_header.isra.11+0x9b/0x1c8
[    2.533229]  [<ffffffff810910e6>] ? __blocking_notifier_call_chain+0x56/0x70
[    2.552781]  [<ffffffff81172689>] __out_of_memory+0x539/0x550
[    2.556808]  [<ffffffff81176d45>] ? get_page_from_freelist+0x135/0x9e0
[    2.561588]  [<ffffffff8117283b>] out_of_memory+0x5b/0x80
[    2.565610]  [<ffffffff81177fcb>] __alloc_pages_nodemask+0x8db/0xa10
[    2.570050]  [<ffffffff811b95c8>] alloc_page_interleave+0x48/0xa0
[    2.574379]  [<ffffffff811b9c35>] alloc_pages_current+0xf5/0x120
[    2.578832]  [<ffffffff8116e567>] __page_cache_alloc+0xb7/0xe0
[    2.583083]  [<ffffffff8116f1ea>] pagecache_get_page+0xfa/0x1a0
[    2.587463]  [<ffffffff81203247>] ? inode_to_bdi+0x27/0x60
[    2.591616]  [<ffffffff8116f2ba>] grab_cache_page_write_begin+0x2a/0x50
[    2.596212]  [<ffffffff812013ec>] simple_write_begin+0x2c/0x1a0
[    2.600580]  [<ffffffff8116e3bf>] generic_perform_write+0xbf/0x1b0
[    2.605094]  [<ffffffff8131bcc6>] ? security_inode_need_killpriv+0x16/0x20
[    2.610036]  [<ffffffff811704d8>] __generic_file_write_iter+0x168/0x1b0
[    2.614732]  [<ffffffff817858d2>] ? preempt_schedule_common+0x22/0x40
[    2.619288]  [<ffffffff81170608>] generic_file_write_iter+0xe8/0x1f0
[    2.623871]  [<ffffffff81d9494b>] ? bunzip2+0x41f/0x41f
[    2.627617]  [<ffffffff811d7871>] __vfs_write+0xb1/0xf0
[    2.631561]  [<ffffffff811d7f29>] vfs_write+0xa9/0x1b0
[    2.635215]  [<ffffffff81d9494b>] ? bunzip2+0x41f/0x41f
[    2.638931]  [<ffffffff811d8d16>] SyS_write+0x46/0xb0
[    2.642806]  [<ffffffff813c0d13>] ? zlib_inflate+0xd63/0x1c60
[    2.646977]  [<ffffffff81d55eb4>] xwrite+0x2a/0x5f
[    2.650536]  [<ffffffff81d55f74>] do_copy+0x8b/0xba
[    2.654309]  [<ffffffff81d55b6d>] write_buffer+0x24/0x36
[    2.658357]  [<ffffffff81d55bab>] flush_buffer+0x2c/0x87
[    2.662184]  [<ffffffff81d55b7f>] ? write_buffer+0x36/0x36
[    2.666383]  [<ffffffff81d94bee>] __gunzip+0x299/0x341
[    2.670127]  [<ffffffff81d56709>] ? clean_rootfs+0x14d/0x14d
[    2.674574]  [<ffffffff81d94ca7>] gunzip+0x11/0x13
[    2.678358]  [<ffffffff81d55ace>] ? md_run_setup+0x9c/0x9c
[    2.682348]  [<ffffffff81d5638d>] unpack_to_rootfs+0x14d/0x271
[    2.686550]  [<ffffffff81d55ace>] ? md_run_setup+0x9c/0x9c
[    2.690816]  [<ffffffff81d5676a>] populate_rootfs+0x61/0x106
[    2.695034]  [<ffffffff810020fc>] do_one_initcall+0x8c/0x1c0
[    2.699175]  [<ffffffff81d54109>] kernel_init_freeable+0x196/0x223
[    2.703790]  [<ffffffff817778c0>] ? rest_init+0x80/0x80
[    2.707667]  [<ffffffff817778ce>] kernel_init+0xe/0xf0
[    2.711381]  [<ffffffff8178a362>] ret_from_fork+0x42/0x70
[    2.715515]  [<ffffffff817778c0>] ? rest_init+0x80/0x80
[    2.719356] Mem-Info:
[    2.721439] active_anon:0 inactive_anon:0 isolated_anon:0
[    2.721439]  active_file:10364 inactive_file:0 isolated_file:0
[    2.721439]  unevictable:73017 dirty:0 writeback:0 unstable:0
[    2.721439]  slab_reclaimable:2000 slab_unreclaimable:1361
[    2.721439]  mapped:0 shmem:0 pagetables:0 bounce:0
[    2.721439]  free:0 free_pcp:29 free_cma:0
[    2.742687] Node 0 DMA free:0kB min:0kB low:0kB high:0kB active_anon:0kB inactive_anon:0kB active_file:1920kB inactive_file:0kB unevictable:13924kB isolated(anon):0kB isolated(file):0kB present:15992kB managed:15908kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:64kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:13924 all_unreclaimable? yes
[    2.770146] lowmem_reserve[]: 0 0 0 0
[    2.775003] Node 0 DMA32 free:0kB min:0kB low:0kB high:0kB active_anon:0kB inactive_anon:0kB active_file:39536kB inactive_file:0kB unevictable:278144kB isolated(anon):0kB isolated(file):0kB present:499696kB managed:335744kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:7936kB slab_unreclaimable:5444kB kernel_stack:2560kB pagetables:0kB unstable:0kB bounce:0kB free_pcp:116kB local_pcp:76kB free_cma:0kB writeback_tmp:0kB pages_scanned:278144 all_unreclaimable? yes
[    2.804325] lowmem_reserve[]: 0 0 0 0
[    2.809334] Node 0 DMA: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
[    2.822267] Node 0 DMA32: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 0kB
[    2.835423] 83386 total pagecache pages
[    2.838393] 0 pages in swap cache
[    2.841178] Swap cache stats: add 0, delete 0, find 0/0
[    2.844974] Free swap  = 0kB
[    2.847517] Total swap = 0kB
[    2.850022] 128922 pages RAM
[    2.852431] 0 pages HighMem/MovableOnly
[    2.855658] 41009 pages reserved
[    2.858238] 0 pages hwpoisoned
[    2.860857] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[    2.867237] Kernel panic - not syncing: Out of memory and no killable processes...
[    2.867237] 
[    2.871227] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.1.16 #50
[    2.871227] Hardware name: Xen HVM domU, BIOS 4.4.1 06/11/2015
[    2.871227]  00000000000200d2 ffff880014e4b6a8 ffffffff81782a79 0000000000001aca
[    2.871227]  ffffffff81a7cc80 ffff880014e4b728 ffffffff81780835 0000000000000000
[    2.871227]  0000000000000008 ffff880014e4b738 ffff880014e4b6d8 ffff880014e4b718
[    2.871227] Call Trace:
[    2.871227]  [<ffffffff81782a79>] dump_stack+0x45/0x57
[    2.871227]  [<ffffffff81780835>] panic+0xc1/0x1f5
[    2.871227]  [<ffffffff81172697>] __out_of_memory+0x547/0x550
[    2.871227]  [<ffffffff81176d45>] ? get_page_from_freelist+0x135/0x9e0
[    2.871227]  [<ffffffff8117283b>] out_of_memory+0x5b/0x80
[    2.871227]  [<ffffffff81177fcb>] __alloc_pages_nodemask+0x8db/0xa10
[    2.871227]  [<ffffffff811b95c8>] alloc_page_interleave+0x48/0xa0
[    2.871227]  [<ffffffff811b9c35>] alloc_pages_current+0xf5/0x120
[    2.871227]  [<ffffffff8116e567>] __page_cache_alloc+0xb7/0xe0
[    2.871227]  [<ffffffff8116f1ea>] pagecache_get_page+0xfa/0x1a0
[    2.871227]  [<ffffffff81203247>] ? inode_to_bdi+0x27/0x60
[    2.871227]  [<ffffffff8116f2ba>] grab_cache_page_write_begin+0x2a/0x50
[    2.871227]  [<ffffffff812013ec>] simple_write_begin+0x2c/0x1a0
[    2.871227]  [<ffffffff8116e3bf>] generic_perform_write+0xbf/0x1b0
[    2.871227]  [<ffffffff8131bcc6>] ? security_inode_need_killpriv+0x16/0x20
[    2.871227]  [<ffffffff811704d8>] __generic_file_write_iter+0x168/0x1b0
[    2.871227]  [<ffffffff817858d2>] ? preempt_schedule_common+0x22/0x40
[    2.871227]  [<ffffffff81170608>] generic_file_write_iter+0xe8/0x1f0
[    2.871227]  [<ffffffff81d9494b>] ? bunzip2+0x41f/0x41f
[    2.871227]  [<ffffffff811d7871>] __vfs_write+0xb1/0xf0
[    2.871227]  [<ffffffff811d7f29>] vfs_write+0xa9/0x1b0
[    2.871227]  [<ffffffff81d9494b>] ? bunzip2+0x41f/0x41f
[    2.871227]  [<ffffffff811d8d16>] SyS_write+0x46/0xb0
[    2.871227]  [<ffffffff813c0d13>] ? zlib_inflate+0xd63/0x1c60
[    2.871227]  [<ffffffff81d55eb4>] xwrite+0x2a/0x5f
[    2.871227]  [<ffffffff81d55f74>] do_copy+0x8b/0xba
[    2.871227]  [<ffffffff81d55b6d>] write_buffer+0x24/0x36
[    2.871227]  [<ffffffff81d55bab>] flush_buffer+0x2c/0x87
[    2.871227]  [<ffffffff81d55b7f>] ? write_buffer+0x36/0x36
[    2.871227]  [<ffffffff81d94bee>] __gunzip+0x299/0x341
[    2.871227]  [<ffffffff81d56709>] ? clean_rootfs+0x14d/0x14d
[    2.871227]  [<ffffffff81d94ca7>] gunzip+0x11/0x13
[    2.871227]  [<ffffffff81d55ace>] ? md_run_setup+0x9c/0x9c
[    2.871227]  [<ffffffff81d5638d>] unpack_to_rootfs+0x14d/0x271
[    2.871227]  [<ffffffff81d55ace>] ? md_run_setup+0x9c/0x9c
[    2.871227]  [<ffffffff81d5676a>] populate_rootfs+0x61/0x106
[    2.871227]  [<ffffffff810020fc>] do_one_initcall+0x8c/0x1c0
[    2.871227]  [<ffffffff81d54109>] kernel_init_freeable+0x196/0x223
[    2.871227]  [<ffffffff817778c0>] ? rest_init+0x80/0x80
[    2.871227]  [<ffffffff817778ce>] kernel_init+0xe/0xf0
[    2.871227]  [<ffffffff8178a362>] ret_from_fork+0x42/0x70
[    2.871227]  [<ffffffff817778c0>] ? rest_init+0x80/0x80

**Comment by kewinrausch** [comment] 2016-02-16 11:56
I can provide an additional test: I just downloaded and compiled+installed linux kernel 4.1.16 **without** IRATI to check if the problem somewhat related. 
**Result:** the kernel still crash on load (and for the same reason).

Maybe is something about what options are chosen when you compile (I maintain the standard offered one by the menuconfig).

**Comment by vmaffione** [comment] 2016-02-16 12:06
Right, I was thinking the same. I can provide the one I use for me, if you
wish.

2016-02-16 12:56 GMT+01:00 Kewin Rausch <notifications@github.com>:

> I can provide an additional test: I just downloaded and compiled+installed
> linux kernel 4.1.16 *without* IRATI to check if the problem somewhat
> related.
> *Result:* the kernel still crash on load (and for the same reason).
>
> Maybe is something about what options are chosen when you compile (I
> maintain the standard offered one by the menuconfig).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/issues/784#issuecomment-184653798>.
>



-- 
Vincenzo Maffione

**Comment by kewinrausch** [comment] 2016-02-16 12:19
Maybe if we diff such configuration we can find what can cause the problem.
Try to send me the configuration file via mail, so i can answer to you with the diff trace.

**Comment by edugrasa** [comment] 2016-02-16 13:10
@kewinrausch once you know the differences here, could you post them in this thread? I'll also try with XEN.

**Comment by vmaffione** [comment] 2016-04-12 08:45
Not related to IRATI

**Closed by vmaffione** 2016-04-12 08:45 UTC
