### ISSUE TITLE
Shim tcp does not support 2 flows at the same time

### ISSUE THREAD

**Issue by bernatgaston** [IRATI/stack#596] opened 2015-05-13 14:49 UTC
When second flow is asked it gives a kernel malfunction

[12622.004862] rina-shim-tcp-udp(DBG): TCP flow added
[12622.010240] rina-shim-tcp-udp(DBG): Added flow to the list
[12622.016555] rina-rfifo(DBG): FIFO f1f01f08 created successfully
[12622.022525] rina-shim-tcp-udp(DBG): Queue has been created
[12622.028513] rina-ipcp-utils(DBG): Name at f4044c60 finalized successfully
[12622.034915] rina-rnl-utils(DBG): Result of genlmesg_end: 192
[12622.041184] rina-rnl-utils(DBG): Going to send NL unicast message (type = 12, seq-num 2, port = 1)
[12622.050137] rina-rnl-utils(DBG): Unicast NL message sent (type = 12, seq-num 2, port = 1)
[12622.060225] rina-ipcp-utils(DBG): Name at f4044c60 finalized successfully
[12622.067185] rina-ipcp-utils(DBG): Name at f4044c60 destroyed successfully
[12622.067895] rina-rnl(DBG): Dispatching message (skb-in=f092b240, info=c20fdb44, attrs=f47f5620)
[12622.067896] rina-rnl(DBG): Multiplexing message type 14
[12622.067898] rina-rnl(DBG): Fetching handler callback and data
[12622.067900] rina-rnl(DBG): Gonna call f9037e80(c217f840, f092b240, c20fdb44)
[12622.067902] rina-rnl-utils(DBG): RINA Netlink parser started ...
[12622.067903] rina-rnl-utils(DBG): msg at f1f06680 / msg->attrs at f4fe6840
[12622.067904] rina-rnl-utils(DBG):   src-ipc-id: 3
[12622.067905] rina-rnl-utils(DBG):   dst-ipc-id: 2
[12622.068131] rina-rfifo(DBG): FIFO f1f01f08 destroyed successfully
[12622.068133] rina-rnl(DBG): Message 14 handled successfully
[12622.113142] rina-shim-tcp-udp(DBG): TCP flow created
[12622.117729] rina-shim-tcp-udp(DBG): TCP/UDP processing returned 0
[12622.121524] rina-shim-tcp-udp(DBG): Worker finished for now
[12622.124895] rina-shim-tcp-udp(DBG): Worker on efb52f40
[12622.130208] BUG: unable to handle kernel NULL pointer dereference at 00000018
[12622.133994] IP: [<c150693c>] kernel_getsockname+0xc/0x20
[12622.134061] *pde = 00000000 
[12622.134061] Oops: 0000 [#1] SMP 
[12622.134061] Modules linked in: rina_default_plugin normal_ipcp shim_tcp_udp shim_eth_vlan rinarp arp826 rina_personality_default nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbmouse usbhid hid e1000 floppy
[12622.134061] CPU: 0 PID: 3962 Comm: kworker/u17:0 Not tainted 3.15.0 #14
[12622.134061] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[12622.134061] Workqueue: shim-tcp-udp-rwq tcp_udp_rcv_worker [shim_tcp_udp]
[12622.168103] task: f0bd28b0 ti: efa6c000 task.ti: efa6c000
[12622.168103] EIP: 0060:[<c150693c>] EFLAGS: 00010282 CPU: 0
[12622.168103] EIP is at kernel_getsockname+0xc/0x20
[12622.168103] EAX: 00000000 EBX: 00000000 ECX: efa6dee4 EDX: efa6deec
[12622.168103] ESI: efb52f40 EDI: 00000220 EBP: efa6deb8 ESP: efa6deb0
[12622.168103]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[12622.168103] CR0: 8005003b CR2: 00000018 CR3: 30ac4000 CR4: 000006d0
[12622.168103] Stack:
[12622.168103]  f821bd04 00000000 efa6df08 f82181bd f821bd04 efb52f40 f4044730 c217ff80
[12622.168103]  00000000 f08b4100 f821d268 f821d260 f4044c90 00000010 f08b4100 f08b4158
[12622.168103]  00000220 efa6df08 c105a6a1 f821d268 c22e2000 00000220 efa6df40 c105a80b
[12622.168103] Call Trace:
[12622.168103]  [<f82181bd>] tcp_udp_rcv_worker+0xbd/0x4d0 [shim_tcp_udp]
[12622.168103]  [<c105a6a1>] ? pwq_dec_nr_in_flight+0x41/0x90
[12622.168103]  [<c105a80b>] process_one_work+0x11b/0x3b0
[12622.168103]  [<c104f262>] ? mod_timer+0x122/0x180
[12622.168103]  [<c105abc9>] worker_thread+0xf9/0x320
[12622.168103]  [<c105aad0>] ? process_scheduled_works+0x30/0x30
[12622.168103]  [<c106089b>] kthread+0x9b/0xb0
[12622.168103]  [<c1617181>] ret_from_kernel_thread+0x21/0x30
[12622.168103]  [<c1060800>] ? flush_kthread_worker+0x70/0x70
[12622.168103] Code: 8b 75 08 8b 58 18 89 34 24 ff 53 10 8b 5d f8 8b 75 fc 89 ec 5d c3 89 f6 8d bc 27 00 00 00 00 55 89 e5 53 83 ec 04 66 66 66 66 90 <8b> 58 18 c7 04 24 00 00 00 00 ff 53 1c 83 c4 04 5b 5d c3 90 55
[12622.168103] EIP: [<c150693c>] kernel_getsockname+0xc/0x20 SS:ESP 0068:efa6deb0
[12622.168103] CR2: 0000000000000018
[12622.168103] ---[ end trace 61594e86402f6438 ]---
[12622.168103] BUG: sleeping function called from invalid context at kernel/locking/rwsem.c:20
[12622.168103] in_atomic(): 0, irqs_disabled(): 1, pid: 3962, name: kworker/u17:0
[12622.168103] CPU: 0 PID: 3962 Comm: kworker/u17:0 Tainted: G      D       3.15.0 #14
[12622.168103] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[12622.168103] Workqueue: shim-tcp-udp-rwq tcp_udp_rcv_worker [shim_tcp_udp]
[12622.168103]  00000000 00000000 efa6dcc8 c1604ccf 00000f7a efa6dce8 c1068df7 c17d6a70
[12622.168103]  00000000 00000001 00000f7a f0bd2c78 f4fa3958 efa6dcf4 c160e50c f0bd28b0
[12622.168103]  efa6dd0c c10532b3 ffffffff 00000000 00000009 00000046 efa6dd60 c1044d23
[12622.168103] Call Trace:
[12622.168103]  [<c1604ccf>] dump_stack+0x48/0x60
[12622.168103]  [<c1068df7>] __might_sleep+0xc7/0x100
[12622.168103]  [<c160e50c>] down_read+0x1c/0x30
[12622.168103]  [<c10532b3>] exit_signals+0x23/0x110
[12622.168103]  [<c1044d23>] do_exit+0x93/0x960
[12622.416294] rina-ipcp-utils(DBG): Name at f4fe6840 finalized successfully
[12622.416295] rina-syscalls(DBG): Handling personality hook allocate_port
[12622.416296] rina-syscalls(DBG): Calling personality hook allocate_port
[12622.416297] rina-personality-default(DBG): Calling wrapped function
[12622.416300] rina-pidm(DBG): The pidm bitmap find returned id 92 (bad = -1)
[12622.416301] rina-pidm(DBG): Bitmap allocation completed successfully (id = 92)
[12622.416304] rina-kfa(DBG): Flow pre-bound to port-id 93
[12622.416306] rina-ipcp-utils(DBG): Name at f4fe6840 finalized successfully
[12622.416306] rina-ipcp-utils(DBG): Name at f4fe6840 destroyed successfully
[12622.416815] rina-syscalls(DBG): Handling personality hook deallocate_port
[12622.416815] rina-syscalls(DBG): Calling personality hook deallocate_port
[12622.416816] rina-personality-default(DBG): Calling wrapped function
[12622.416817] rina-normal-ipc(ERR): Could not find flow 93 to deallocate
[12622.416818] rina-kipcm(ERR): Failed deallocate flow request for port id: 93
[12622.168103]  [<c1601d3f>] ? printk+0x4d/0x4f
[12622.168103]  [<c1042e0f>] ? print_oops_end_marker+0x2f/0x40
[12622.168103]  [<c1610805>] oops_end+0x85/0xc0
[12622.168103]  [<c160120c>] no_context+0x1a6/0x1ae
[12622.168103]  [<c1601336>] __bad_area_nosemaphore+0x122/0x12a
[12622.168103]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.168103]  [<c1601355>] bad_area_nosemaphore+0x17/0x19
[12622.168103]  [<c16129e2>] __do_page_fault+0xd2/0x510
[12622.168103]  [<c160fd19>] ? apic_timer_interrupt+0x2d/0x34
[12622.168103]  [<c10942af>] ? vprintk_emit+0x1ef/0x4e0
[12622.168103]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.168103]  [<c1612e2b>] do_page_fault+0xb/0x10
[12622.168103]  [<c161008a>] error_code+0x5a/0x60
[12622.168103]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.168103]  [<c150693c>] ? kernel_getsockname+0xc/0x20
[12622.168103]  [<f82181bd>] tcp_udp_rcv_worker+0xbd/0x4d0 [shim_tcp_udp]
[12622.168103]  [<c105a6a1>] ? pwq_dec_nr_in_flight+0x41/0x90
[12622.168103]  [<c105a80b>] process_one_work+0x11b/0x3b0
[12622.168103]  [<c104f262>] ? mod_timer+0x122/0x180
[12622.168103]  [<c105abc9>] worker_thread+0xf9/0x320
[12622.168103]  [<c105aad0>] ? process_scheduled_works+0x30/0x30
[12622.168103]  [<c106089b>] kthread+0x9b/0xb0
[12622.168103]  [<c1617181>] ret_from_kernel_thread+0x21/0x30
[12622.168103]  [<c1060800>] ? flush_kthread_worker+0x70/0x70
[12622.529626] BUG: unable to handle kernel paging request at ffffffec
[12622.533648] IP: [<c10609cf>] kthread_data+0xf/0x20
[12622.533648] *pde = 019e3067 *pte = 00000000 
[12622.533648] Oops: 0000 [#2] SMP 
[12622.533648] Modules linked in: rina_default_plugin normal_ipcp shim_tcp_udp shim_eth_vlan rinarp arp826 rina_personality_default nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbmouse usbhid hid e1000 floppy
[12622.533648] CPU: 1 PID: 3962 Comm: kworker/u17:0 Tainted: G      D       3.15.0 #14
[12622.533648] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[12622.533648] task: f0bd28b0 ti: efa6c000 task.ti: efa6c000
[12622.533648] EIP: 0060:[<c10609cf>] EFLAGS: 00010002 CPU: 1
[12622.533648] EIP is at kthread_data+0xf/0x20
[12622.533648] EAX: 00000000 EBX: 00000001 ECX: 00000000 EDX: 00000001
[12622.533648] ESI: f0bd2c2c EDI: f0bd28b0 EBP: efa6dc84 ESP: efa6dc7c
[12622.533648]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[12622.533648] CR0: 8005003b CR2: 00000014 CR3: 34fc4000 CR4: 000006d0
[12622.533648] Stack:
[12622.533648]  c105b7a0 00000001 efa6dd04 c160c55a 00000013 0000001a c22f9dc0 00000001
[12622.533648]  c19d66a0 efa6dcac c109d2fc c19d66a0 f59836a0 f0bd28b0 efa6dcd4 c1151dbc
[12622.533648]  00000246 c1040a29 00040a29 f0bd28b0 f0bd28b0 00000000 efa6dce0 c109d2fc
[12622.533648] Call Trace:
[12622.533648]  [<c105b7a0>] ? wq_worker_sleeping+0x10/0x80
[12622.533648]  [<c160c55a>] __schedule+0x55a/0x790
[12622.533648]  [<c109d2fc>] ? call_rcu_sched+0x1c/0x20
[12622.533648]  [<c1151dbc>] ? kmem_cache_free+0xfc/0x170
[12622.533648]  [<c1040a29>] ? __cleanup_sighand+0x29/0x30
[12622.533648]  [<c109d2fc>] ? call_rcu_sched+0x1c/0x20
[12622.533648]  [<c1043d82>] ? release_task+0x2f2/0x420
[12622.533648]  [<c1102501>] ? account_event_cpu+0x1/0x50
[12622.533648]  [<c10bc94b>] ? cgroup_exit+0x9b/0xc0
[12622.533648]  [<c160c7f3>] schedule+0x23/0x60
[12622.533648]  [<c1045187>] do_exit+0x4f7/0x960
[12622.533648]  [<c1610805>] oops_end+0x85/0xc0
[12622.533648]  [<c160120c>] no_context+0x1a6/0x1ae
[12622.533648]  [<c1601336>] __bad_area_nosemaphore+0x122/0x12a
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c1601355>] bad_area_nosemaphore+0x17/0x19
[12622.533648]  [<c16129e2>] __do_page_fault+0xd2/0x510
[12622.533648]  [<c160fd19>] ? apic_timer_interrupt+0x2d/0x34
[12622.533648]  [<c10942af>] ? vprintk_emit+0x1ef/0x4e0
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c1612e2b>] do_page_fault+0xb/0x10
[12622.533648]  [<c161008a>] error_code+0x5a/0x60
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c150693c>] ? kernel_getsockname+0xc/0x20
[12622.533648]  [<f82181bd>] tcp_udp_rcv_worker+0xbd/0x4d0 [shim_tcp_udp]
[12622.533648]  [<c105a6a1>] ? pwq_dec_nr_in_flight+0x41/0x90
[12622.533648]  [<c105a80b>] process_one_work+0x11b/0x3b0
[12622.533648]  [<c104f262>] ? mod_timer+0x122/0x180
[12622.533648]  [<c105abc9>] worker_thread+0xf9/0x320
[12622.533648]  [<c105aad0>] ? process_scheduled_works+0x30/0x30
[12622.533648]  [<c106089b>] kthread+0x9b/0xb0
[12622.533648]  [<c1617181>] ret_from_kernel_thread+0x21/0x30
[12622.533648]  [<c1060800>] ? flush_kthread_worker+0x70/0x70
[12622.533648] Code: 66 66 66 90 64 a1 34 06 9d c1 8b 80 50 03 00 00 5d 8b 40 e4 c1 e8 02 83 e0 01 c3 90 55 89 e5 66 66 66 66 90 8b 80 50 03 00 00 5d <8b> 40 ec c3 8d b6 00 00 00 00 8d bc 27 00 00 00 00 55 89 e5 83
[12622.533648] EIP: [<c10609cf>] kthread_data+0xf/0x20 SS:ESP 0068:efa6dc7c
[12622.533648] CR2: 00000000ffffffec
[12622.533648] ---[ end trace 61594e86402f6439 ]---
[12622.533648] Fixing recursive fault but reboot is needed!
[12622.533648] BUG: scheduling while atomic: kworker/u17:0/3962/0x00000004
[12622.533648] Modules linked in: rina_default_plugin normal_ipcp shim_tcp_udp shim_eth_vlan rinarp arp826 rina_personality_default nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbmouse usbhid hid e1000 floppy
[12622.533648] CPU: 1 PID: 3962 Comm: kworker/u17:0 Tainted: G      D       3.15.0 #14
[12622.533648] Hardware name: Xen HVM domU, BIOS 4.0.1 05/03/2013
[12622.533648]  00000000 00000000 efa6da38 c1604ccf 00000001 efa6da50 c16019cc c17d6a00
[12622.533648]  f0bd2c78 00000f7a 00000004 efa6dad0 c160c70a 00000000 00000977 00000977
[12622.533648]  0000002c c19d66a0 00000001 efa6dab8 c19d66a0 f59836a0 f0bd28b0 00000000
[12622.533648] Call Trace:
[12622.533648]  [<c1604ccf>] dump_stack+0x48/0x60
[12622.533648]  [<c16019cc>] __schedule_bug+0x50/0x5e
[12622.533648]  [<c160c70a>] __schedule+0x70a/0x790
[12622.533648]  [<c1601d3f>] ? printk+0x4d/0x4f
[12622.533648]  [<c160c7f3>] schedule+0x23/0x60
[12622.533648]  [<c10455ae>] do_exit+0x91e/0x960
[12622.533648]  [<c1601d3f>] ? printk+0x4d/0x4f
[12622.533648]  [<c1042e0f>] ? print_oops_end_marker+0x2f/0x40
[12622.533648]  [<c1610805>] oops_end+0x85/0xc0
[12622.533648]  [<c160120c>] no_context+0x1a6/0x1ae
[12622.533648]  [<c1601336>] __bad_area_nosemaphore+0x122/0x12a
[12622.533648]  [<c107245f>] ? sched_clock_cpu+0xff/0x150
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c1601355>] bad_area_nosemaphore+0x17/0x19
[12622.533648]  [<c16129e2>] __do_page_fault+0xd2/0x510
[12622.533648]  [<c1076549>] ? dequeue_entity+0x149/0x630
[12622.533648]  [<c1076d7e>] ? dequeue_task_fair+0x34e/0x670
[12622.533648]  [<c107852c>] ? enqueue_entity+0x55c/0xcd0
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c1612e2b>] do_page_fault+0xb/0x10
[12622.533648]  [<c161008a>] error_code+0x5a/0x60
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c10609cf>] ? kthread_data+0xf/0x20
[12622.533648]  [<c105b7a0>] ? wq_worker_sleeping+0x10/0x80
[12622.533648]  [<c160c55a>] __schedule+0x55a/0x790
[12622.533648]  [<c109d2fc>] ? call_rcu_sched+0x1c/0x20
[12622.533648]  [<c1151dbc>] ? kmem_cache_free+0xfc/0x170
[12622.533648]  [<c1040a29>] ? __cleanup_sighand+0x29/0x30
[12622.533648]  [<c109d2fc>] ? call_rcu_sched+0x1c/0x20
[12622.533648]  [<c1043d82>] ? release_task+0x2f2/0x420
[12622.533648]  [<c1102501>] ? account_event_cpu+0x1/0x50
[12622.533648]  [<c10bc94b>] ? cgroup_exit+0x9b/0xc0
[12622.533648]  [<c160c7f3>] schedule+0x23/0x60
[12622.533648]  [<c1045187>] do_exit+0x4f7/0x960
[12622.533648]  [<c1610805>] oops_end+0x85/0xc0
[12622.533648]  [<c160120c>] no_context+0x1a6/0x1ae
[12622.533648]  [<c1601336>] __bad_area_nosemaphore+0x122/0x12a
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c1601355>] bad_area_nosemaphore+0x17/0x19
[12622.533648]  [<c16129e2>] __do_page_fault+0xd2/0x510
[12622.533648]  [<c160fd19>] ? apic_timer_interrupt+0x2d/0x34
[12622.533648]  [<c10942af>] ? vprintk_emit+0x1ef/0x4e0
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c1612e2b>] do_page_fault+0xb/0x10
[12622.533648]  [<c161008a>] error_code+0x5a/0x60
[12622.533648]  [<c1612e20>] ? __do_page_fault+0x510/0x510
[12622.533648]  [<c150693c>] ? kernel_getsockname+0xc/0x20
[12622.533648]  [<f82181bd>] tcp_udp_rcv_worker+0xbd/0x4d0 [shim_tcp_udp]
[12622.533648]  [<c105a6a1>] ? pwq_dec_nr_in_flight+0x41/0x90
[12622.533648]  [<c105a80b>] process_one_work+0x11b/0x3b0
[12622.533648]  [<c104f262>] ? mod_timer+0x122/0x180
[12622.533648]  [<c105abc9>] worker_thread+0xf9/0x320
[12622.533648]  [<c105aad0>] ? process_scheduled_works+0x30/0x30
[12622.533648]  [<c106089b>] kthread+0x9b/0xb0
[12622.533648]  [<c1617181>] ret_from_kernel_thread+0x21/0x30
[12622.533648]  [<c1060800>] ? flush_kthread_worker+0x70/0x70

**Comment by dstaesse** [comment] 2015-05-19 09:56
This situation is also reported in IRATI D4.3 (p56):
http://irati.eu/wp-content/uploads/2012/07/IRATI-D4.3.pdf
So, if confirmed, it's present in the stack at least since v1.0.0. 
In v.1.0.0, the issue happens for normal over shim-tcp-udp as well as normal over shim-eth-vlan.
The same setup running the app directly over the shims worked in v1.0.0.

**Comment by edugrasa** [comment] 2016-02-10 17:00
Tried with both TCP and UDP, app over shim 4 concurrent flows multiple times. No issues, closing.

**Closed by edugrasa** 2016-02-10 17:00 UTC
Labels: bug
