### ISSUE TITLE
pristine-1.5: buffer-ok: unable to handle kernel paging request

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#928] opened 2016-05-12 14:34 UTC
I got this other crash when doing additional test to find out where is located the problem with #927.
The test was a totally default one, just with rate based FC instead of window one.

```
May 12 15:40:45 s4 kernel: [  688.598306] rina-shim-eth-vlan(INFO): shim-eth-vlan initialized
May 12 15:40:45 s4 kernel: [  688.598327] rina-ipcp-factories(INFO): Factory 'shim-eth-vlan' registered successfully
May 12 15:40:45 s4 kernel: [  688.616345] rina-ps-factory(INFO): policy-set 'default' published successfully
May 12 15:40:45 s4 kernel: [  688.616347] rina-rina-default-plugin(INFO): RMT default policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.616349] rina-ps-factory(INFO): policy-set 'default' published successfully
May 12 15:40:45 s4 kernel: [  688.616350] rina-rina-default-plugin(INFO): DTP default policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.616351] rina-ps-factory(INFO): policy-set 'default' published successfully
May 12 15:40:45 s4 kernel: [  688.616352] rina-rina-default-plugin(INFO): DTCP default policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.616354] rina-ps-factory(INFO): policy-set 'default' published successfully
May 12 15:40:45 s4 kernel: [  688.616355] rina-rina-default-plugin(INFO): PFF default policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.616356] rina-ps-factory(INFO): policy-set 'default' published successfully
May 12 15:40:45 s4 kernel: [  688.616357] rina-rina-default-plugin(INFO): SDU Protection default Crypto policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.616359] rina-ps-factory(INFO): policy-set 'CRC32' published successfully
May 12 15:40:45 s4 kernel: [  688.616360] rina-rina-default-plugin(INFO): SDU Protection default error check policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.616361] rina-ps-factory(INFO): policy-set 'default' published successfully
May 12 15:40:45 s4 kernel: [  688.616362] rina-rina-default-plugin(INFO): SDU Protection default TTL policy set loaded successfully
May 12 15:40:45 s4 kernel: [  688.635260] rina-ipcp-factories(INFO): Factory 'normal-ipc' registered successfully
May 12 15:40:45 s4 kernel: [  689.076590] rina-kipcm(INFO): IPC Manager started. It is listening at NL port-id 1
May 12 15:40:46 s4 kernel: [  689.153249] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153254] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153256] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153258] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153260] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153262] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153264] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153266] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153744] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153751] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153754] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153756] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153758] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153760] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153762] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.153764] rina-shim-eth-utils(INFO): shim-eth-qdisc-init: max size: 50, enable thres: 10
May 12 15:40:46 s4 kernel: [  689.296260] rina-rmt(INFO): RMT PS to be selected: default
May 12 15:40:46 s4 kernel: [  689.296272] rina-rmt-ps-default(WARN): No PS param q_max
May 12 15:40:46 s4 kernel: [  689.296273] rina-rmt(INFO): PFF PS to be selected: default
May 12 15:40:46 s4 kernel: [  689.296274] rina-ps-factory(INFO): Policy-set 'default' already selected
May 12 15:40:46 s4 kernel: [  689.296276] rina-normal-ipc(INFO): No SDU protection config specified, using default
May 12 15:43:51 s4 kernel: [  874.699805] BUG: unable to handle kernel paging request at 000000cb000000cc
May 12 15:43:51 s4 kernel: [  874.699846] IP: [<ffffffff81564b6a>] buffer_is_ok+0xa/0x30
May 12 15:43:51 s4 kernel: [  874.699878] PGD 0
May 12 15:43:51 s4 kernel: [  874.699891] Oops: 0000 [#1] SMP
May 12 15:43:51 s4 kernel: [  874.699908] Modules linked in: normal_ipcp rina_default_plugin shim_eth_vlan rinarp arp826 8021q garp mrp stp llc nfsv3 ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd grace fscache sunrpc loop mgag200 snd_pcm intel_powerclamp ttm drm_kms_helper snd_timer coretemp kvm_intel drm kvm snd acpi_cpufreq processor soundcore ehci_pci psmouse iTCO_wdt iTCO_vendor_support thermal_sys lpc_ich joydev serio_raw pcspkr i7core_edac evdev edac_core button mfd_core i2c_i801 ioatdma tpm_tis tpm ext4 crc16 mbcache jbd2 dm_mod sg sd_mod hid_generic usbhid hid ata_generic crc32c_intel ata_piix libata uhci_hcd scsi_mod ehci_hcd usbcore igb usb_common i2c_algo_bit i2c_core dca ptp pps_core
May 12 15:43:51 s4 kernel: [  874.700310] CPU: 0 PID: 4800 Comm: rping Not tainted 4.1.16 #25
May 12 15:43:51 s4 kernel: [  874.700334] Hardware name: Supermicro X8DTT/X8DTT, BIOS 080016  10/05/2010
May 12 15:43:51 s4 kernel: [  874.700360] task: ffff88002e5a2ce0 ti: ffff8801b7ddc000 task.ti: ffff8801b7ddc000
May 12 15:43:51 s4 kernel: [  874.700388] RIP: 0010:[<ffffffff81564b6a>]  [<ffffffff81564b6a>] buffer_is_ok+0xa/0x30
May 12 15:43:51 s4 kernel: [  874.700421] RSP: 0018:ffff8801b7ddfea0  EFLAGS: 00010006
May 12 15:43:51 s4 kernel: [  874.700443] RAX: ffff8800b9e5d540 RBX: ffff8801b54607c0 RCX: ffff8801b7ddff30
May 12 15:43:51 s4 kernel: [  874.700470] RDX: 0000000000000045 RSI: 0000000000000003 RDI: 000000cb000000cc
May 12 15:43:51 s4 kernel: [  874.700496] RBP: 0000000000000286 R08: 0000000000000286 R09: 00000000015b6fd0
May 12 15:43:51 s4 kernel: [  874.700523] R10: 0000000000490655 R11: 0000000000000246 R12: ffff8801b828d400
May 12 15:43:51 s4 kernel: [  874.700550] R13: 0000000000000000 R14: 0000000000000000 R15: ffff8801b7ddfed8
May 12 15:43:51 s4 kernel: [  874.700576] FS:  00007f057bfff700(0000) GS:ffff8801b9a00000(0000) knlGS:0000000000000000
May 12 15:43:51 s4 kernel: [  874.700606] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
May 12 15:43:51 s4 kernel: [  874.700629] CR2: 000000cb000000cc CR3: 0000000334683000 CR4: 00000000000006f0
May 12 15:43:51 s4 kernel: [  874.700655] Stack:
May 12 15:43:51 s4 kernel: [  874.700666]  ffffffff81577c95 0000000300000246 ffff8801b7ddff30 ffff8801b7ddfeb8
May 12 15:43:51 s4 kernel: [  874.700700]  ffff8801b7ddfeb8 ffffffffffffffff ffff8801b704a480 0000000000000400
May 12 15:43:51 s4 kernel: [  874.700734]  ffff8801b704a440 0000000000000400 0000000000000003 0000000000000400
May 12 15:43:51 s4 kernel: [  874.700768] Call Trace:
May 12 15:43:51 s4 kernel: [  874.700784]  [<ffffffff81577c95>] ? kfa_flow_sdu_read+0x385/0x4a0
May 12 15:43:51 s4 kernel: [  874.700811]  [<ffffffff8157f66f>] ? SyS_sdu_read+0x2f/0x100
May 12 15:43:51 s4 kernel: [  874.700834]  [<ffffffff8159011c>] ? system_call_after_swapgs+0x49/0x49
May 12 15:43:51 s4 kernel: [  874.700860]  [<ffffffff81590132>] ? system_call_fastpath+0x16/0x75
May 12 15:43:51 s4 kernel: [  874.700884] Code: c0 e8 f0 4a 02 00 5a 48 c7 c7 f8 64 78 81 31 c0 e9 e1 4a 02 00 66 2e 0f 1f 84 00 00 00 00 00 66 90 66 66 66 66 90 48 85 ff 74 16 <48> 83 3f 00 74 10 48 83 7f 08 00 0f 95 c0 c3 0f 1f 80 00 00 00
May 12 15:43:51 s4 kernel: [  874.701080] RIP  [<ffffffff81564b6a>] buffer_is_ok+0xa/0x30
May 12 15:43:51 s4 kernel: [  874.701105]  RSP <ffff8801b7ddfea0>
May 12 15:43:51 s4 kernel: [  874.701120] CR2: 000000cb000000cc
May 12 15:43:51 s4 kernel: [  874.701135] ---[ end trace 497fb4cc24a6fd5c ]---
May 12 15:44:12 s4 kernel: [  895.746354] INFO: rcu_sched detected stalls on CPUs/tasks: { 3 13} (detected by 11, t=5252 jiffies, g=2908, c=2907, q=484)
May 12 15:44:12 s4 kernel: [  895.746482] Task dump for CPU 3:
May 12 15:44:12 s4 kernel: [  895.746515] swapper/3       R  running task        0     0      1 0x00000008
May 12 15:44:12 s4 kernel: [  895.746587]  0000000000000010 0000000000000246 ffff8801b8617e88 0000000000000018
May 12 15:44:12 s4 kernel: [  895.746668]  ffffffff81438d8c 0000000000000000 0000000000000000 0000000000000096
May 12 15:44:12 s4 kernel: [  895.746746]  ffffffff819021c0 ffffe8fe79ac7ad0 ffff8801b8614000 ffffffff818b0480
May 12 15:44:12 s4 kernel: [  895.749146] Call Trace:
May 12 15:44:12 s4 kernel: [  895.751477]  [<ffffffff81438d8c>] ? cpuidle_enter_state+0x7c/0x200
May 12 15:44:12 s4 kernel: [  895.753832]  [<ffffffff810ae84b>] ? cpu_startup_entry+0x3ab/0x430
May 12 15:44:12 s4 kernel: [  895.756153]  [<ffffffff81049a05>] ? start_secondary+0x185/0x1b0
May 12 15:44:12 s4 kernel: [  895.758439] Task dump for CPU 13:
May 12 15:44:12 s4 kernel: [  895.760705] ksoftirqd/13    R  running task        0    75      2 0x00000008
May 12 15:44:12 s4 kernel: [  895.763032]  000000000000020a 0000000000000001 ffffffff8107434a 0000010000000002
May 12 15:44:12 s4 kernel: [  895.765334]  0000000100023068 ffff8803387f0000 042080400000000a ffff8803387e6ba0
May 12 15:44:12 s4 kernel: [  895.767591]  ffff8803387e6ba0 ffff8803387c44a0 ffffffff8183e080 ffff8803387e6ba0
May 12 15:44:12 s4 kernel: [  895.769789] Call Trace:
May 12 15:44:12 s4 kernel: [  895.771905]  [<ffffffff8107434a>] ? __do_softirq+0x11a/0x290
May 12 15:44:12 s4 kernel: [  895.773996]  [<ffffffff810744e9>] ? run_ksoftirqd+0x29/0x50
May 12 15:44:12 s4 kernel: [  895.776018]  [<ffffffff81090e1f>] ? smpboot_thread_fn+0x14f/0x1c0
May 12 15:44:12 s4 kernel: [  895.777986]  [<ffffffff81090cd0>] ? sort_range+0x30/0x30
May 12 15:44:12 s4 kernel: [  895.779934]  [<ffffffff8108d9d3>] ? kthread+0xd3/0xf0
May 12 15:44:12 s4 kernel: [  895.781854]  [<ffffffff8108d900>] ? kthread_create_on_node+0x180/0x180
May 12 15:44:12 s4 kernel: [  895.783764]  [<ffffffff81590562>] ? ret_from_fork+0x42/0x70
May 12 15:44:12 s4 kernel: [  895.785644]  [<ffffffff8108d900>] ? kthread_create_on_node+0x180/0x180
```

**Comment by edugrasa** [comment] 2017-05-30 08:54
Closing, cannot reproduce (probably got fixed after reworking the pdu/sdu infrastructure)

**Closed by edugrasa** 2017-05-30 08:54 UTC
