### ISSUE TITLE
How to monitor the IRATI prototype?

### ISSUE THREAD

**Issue by KleberLealCIn** [IRATI/stack#937] opened 2016-05-25 00:41 UTC
Hello there,

I am looking for statistics about RINA processing (waiting time, queue size, sdu transmitted/received/retransmitted/discarded, and so on).

I have been searching for them on /proc filesystem but I couldn't find anything.
Are these informations available?

I appreciate any help.

Kleber

**Comment by edugrasa** [comment] 2016-05-25 00:54
We use sysfs, you can find it in /sys/rina if Im not wrong

**Comment by KleberLealCIn** [comment] 2016-06-01 01:01
Hi Grasa,
Thank you for replying.

I spent a time searching for informantions inside the /sys for get this informations, but unfortunately I could find nothing.
The /sys/rina directory have only empty subdirectories and no informations are available.
Probably on the actual prototype development stage that informations aren't available yet. At least when loading the kernel without any special parameter to do so.

Thank you for replying and excuse me for delayed replica.
I was really busy this week and almost forgot it.

Kleber

**Comment by edugrasa** [comment] 2016-06-01 07:43
Hi Kleber,

What branch are you using? (I'd recommend using pristine-1.5). Also, unless you start the IPC Manager and have some IPC Processes running, /sys/rina/ will be empty because well.. there is nothing running ;)

**Comment by vmaffione** [comment] 2016-06-01 07:46
Hi Kleber,
  You may start from here:

https://github.com/IRATI/demonstrator

Take a look at the README and try the IRATI mini-tutorial.

**Comment by KleberLealCIn** [comment] 2016-06-10 22:47
Grasa,
I had a chance to see what are in there.
But I am facing problem when compiling pristine-1.5. I am using the same machine I used when I successful compiled an older version of the prototype. I'll open a new issue for this to keep the post sanity :D.

vmaffione,
I was surprised with the simplicity of this tool.
Is there a way to insert new tools into the rootfs without recreate the entire image?
I started reading the documentation but I think is necessary recompile the entire image, including kernel em filesystem.
The main ideia is include a traffic generator into rootfs and make use of the demonstrator to see how does RINA behave in certain scenarios.

Thank you.

Kleber

**Comment by vmaffione** [comment] 2016-06-11 06:23
What traffic generator would you like to add?
Generating the image is actually straigthforward. The first time it requires some time since buildroot has to download lots of sources and build the whole system. If you do some subsequent additions, buildroot will just build what is missing.

**Comment by KleberLealCIn** [comment] 2016-06-11 18:39
I just downloaded the buildroot available here (https://github.com/IRATI/buildroot) and made simple configuration and it resulted into a image without RINA kernel and tools. All the source code was download from kernel.org and others official repositories just in time.

The traffic generator I mentioned is a modified iperf that was extended by a PhD student here from Federal University of Pernambuco. Unfortunately he moved to another research area and the code was abandoned. Since then it is not working on the most recent version of RINA prototype. 

May you give me a brief overview of how can I use the buildroot to get a RINA enabled image in the end?

Kleber

**Comment by vmaffione** [comment] 2016-06-12 12:17
Hi,
 You simply have to use the irati branch in the https://github.com/IRATI/buildroot repository.
To build the RINA image, you have to
````
$ cp IRATI_BUILDROOT_CONFIG .config
$ make
````

**Comment by KleberLealCIn** [comment] 2016-06-12 13:02
Vincenzo,

I didn't find the IRATI_BUILDROOT_CONFIG file.
I looked for it in both builroot and pristine-1.5 directory but no success.
I just downloaded the buildroot from the IRATI buildroot branch github
repository.


2016-06-12 9:17 GMT-03:00 Vincenzo Maffione <notifications@github.com>:

**Comment by vmaffione** [comment] 2016-06-12 13:08
The file is there

https://github.com/IRATI/buildroot/tree/irati

**Comment by KleberLealCIn** [comment] 2016-06-12 13:23
Thank you, Vincenzo.

I was using a wrong repository (https://github.com/IRATI/buildroot) via
buildroot link on github.com/IRATI.

Kleber

2016-06-12 10:08 GMT-03:00 Vincenzo Maffione <notifications@github.com>:

**Comment by KleberLealCIn** [comment] 2016-06-12 15:29
Vicenzo,

The compilation was aborted.

The last few lines of make output are show below:

checking for mvn... /usr/bin/mvn
configure: Using system headers in output/build/linux-custom/usr/include
checking for ipc_create syscall availability... no
*configure: error: Your system lacks of a necessary syscall*
package/pkg-generic.mk:185: recipe for target
'/home/kleber/buildroot-irati/output/build/librina-kernel-update/.stamp_configured'
failed
make: ***
[/home/kleber/buildroot-irati/output/build/librina-kernel-update/.stamp_configured]
Error 1

Do you know what should I have to do to solve it?

I am running a regular kernel on my computer.
Linux Distribution: Debian Jessie
uname -a output: Linux r2d2 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2
(2016-04-08) x86_64 GNU/Linux


Two other problems I have faced when compiling was easily solved replacing
the absolute paths with the relative ones.

kleber@r2d2:~/buildroot-irati$ diff IRATI_BUILDROOT_CONFIG
IRATI_BUILDROOT_CONFIG_old
297c297
< BR2_ROOTFS_OVERLAY="overlay"
---
> BR2_ROOTFS_OVERLAY="/home/vmaffione/git/nxw/buildroot/overlay"


kleber@r2d2:~/buildroot-irati/package/librina$ diff librina.mk
librina.mk_old
20c20
< LIBRINA_CONF_OPTS = --disable-java-bindings --enable-debug
--with-sysheaders=output/build/linux-custom/usr/include
---
> LIBRINA_CONF_OPTS = --disable-java-bindings --enable-debug
--with-sysheaders=/home/vmaffione/git/nxw/buildroot/output/build/linux-custom/usr/include



2016-06-12 10:23 GMT-03:00 Kleber Alves Leal <kal2@cin.ufpe.br>:

**Comment by vmaffione** [comment] 2016-06-13 10:47
Hi,
  Sorry, I made an error while updating the IRATI branch used by the buildroot config. Pushed the fix, can you give a try?

I'll also try to see if using relative path works. Does it work for you?

**Comment by KleberLealCIn** [comment] 2016-06-14 00:34
Now the compilation process was completed successfully.
The relative path works well for IRATI_BUILDROOT_CONFIG but not for librina.mk, where I needed to fill it with the absolute path reflecting my system.

Although the compilation process have finished successfully the rina-echo-time applications didn't work as expected. See the output below:

# rina-echo-time -c 10
669(1465863402)#librina.logs (DBG): New log level: INFO
669(1465863402)#librina.nl-manager (INFO): Netlink socket connected to local port 669 
Flow allocation time = 5.9768 ms
SDU size = 20, seq = 0, RTT = 0.21843 ms [bad response]
SDU size = 20, seq = 1, RTT = 0.90009 ms [bad response]
SDU size = 20, seq = 2, RTT = 0.92158 ms [bad response]
SDU size = 20, seq = 3, RTT = 0.33009 ms [bad response]
^C

The output of rina-echo-time -l from the pair host was omitted.
When using the original demonstrator image it works well.

**Comment by vmaffione** [comment] 2016-06-14 08:25
Hi,
  I've updated the buildroot code so to avoid hardcoded path at all. Can you please check the latest updates on the irati branch? Morover, please use the update-irati.sh script to update the image.

This said, I also see this weird output (with an image rebuilt right now), It may be that it has nothing to do with the buildroot... maybe something changed in IRATI that causes this? @edugrasa you have some ideas?

Doing some investigations in the meanwhile..

**Comment by vmaffione** [comment] 2016-06-14 10:14
I see the same bad response output using traditional virtual machine images. This means that something went wrong in branch pristine-1.5, so that this output has started appearing recently.

**Comment by vmaffione** [comment] 2016-06-14 10:34
Somehow the different behaviour was caused by this commit: e06053a6ab4bda75815b41389baee76f8fdb7b1b

**Comment by edugrasa** [comment] 2016-06-14 14:23
That's right. I've modified rina-echo-time to adapt to that change: https://github.com/IRATI/stack/pull/960. @vmaffione  could you test and merge it it works? Thanks!

**Comment by KleberLealCIn** [comment] 2016-06-14 18:35
Now it works fine.
@edugrasa: The "bad response" error is solved.
@vmaffione: The script update-irati.sh works well.

Kleber

**Comment by vmaffione** [comment] 2016-06-14 21:41
great!

**Closed** 2016-07-07 13:58 UTC
