### ISSUE TITLE
Pristine-1.4: Multiple instances of AE with the same name in the same node

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#829] opened 2015-12-24 09:00 UTC
If I launch an AE with the **same name on the same node**, there should be the application instance left in order to differentiate the communication. But running multiple clients with the same name on the same machine does make it happens, and they share instance 1 (name-1). When a flow is then closed, all the flows with the same name(but they got different port id) are closed, even if they did not want this (see last log).

This issue is similar to https://github.com/IRATI/stack/issues/779, which was on different client machine but same destination server.

Client side log of 1st instance on server 3:
Script args, just as note, are: client.sh client_name server_name interval(0 = continuous) exp_time avg _bandwidth(0 = do not care)
```
krausch@s3:~/scripts$ sh client.sh s3 s1 0 60 0
21429(1450946304)#librina.logs (DBG): New log level: INFO
21429(1450946304)#librina.nl-manager (INFO): Netlink socket connected to local port 21429
21429(1450946304)#traffic-generator (INFO): starting test
activity_int: 0
21429(1450946364)#traffic-generator (INFO): sent statistics:     45052 SDUs,     63072800 bytes in  60089112 us, 8.3972 Mb/s
```

Client side log of 1st instance on server 3:
```
krausch@s3:~/scripts$ sh client.sh  s3 s1 0 60 0
21461(1450946310)#librina.logs (DBG): New log level: INFO
21461(1450946310)#librina.nl-manager (INFO): Netlink socket connected to local port 21461
21461(1450946310)#traffic-generator (INFO): starting test
activity_int: 0
21461(1450946370)#traffic-generator (INFO): sent statistics:     45058 SDUs,     63081200 bytes in  60091465 us, 8.3980 Mb/s
```

NOTE: You can distinguish the two only because one is launched 5 second later.
Server side log are:
```
krausch@s1:~/scripts$ sh server.sh s1 5000
22852(1450946301)#librina.logs (DBG): New log level: INFO
22852(1450946301)#librina.nl-manager (INFO): Netlink socket connected to local port 22852
22852(1450946304)#traffic-generator (INFO): New flow allocated [port-id = 3]
Port,SDUs,bytes,us,p/s,Mb/s
s3-client-1, 3268, 4575200, 5.5002, 653.330078, 7.317297
22852(1450946310)#traffic-generator (INFO): New flow allocated [port-id = 4]
Port,SDUs,bytes,us,p/s,Mb/s
s3-client-1, 3517, 4923800, 10.5180, 678.897461, 7.603652
s3-client-1, 3406, 4768400, 5.5288, 644.047424, 7.213332
s3-client-1, 3083, 4316200, 15.5070, 607.980530, 6.809382
s3-client-1, 3536, 4950400, 10.5126, 689.694397, 7.724578
s3-client-1, 3332, 4664800, 20.5006, 665.585999, 7.454563
s3-client-1, 3889, 5444600, 15.5264, 738.692322, 8.273354
s3-client-1, 3674, 5143600, 25.5438, 675.582947, 7.566529
s3-client-1, 3474, 4863600, 20.5103, 680.757446, 7.624484
s3-client-1, 3066, 4292400, 30.5143, 596.128174, 6.676636
s3-client-1, 3832, 5364800, 25.5268, 727.362183, 8.146457
s3-client-1, 3245, 4543000, 35.5122, 633.463013, 7.094786
s3-client-1, 3525, 4935000, 30.5118, 688.741943, 7.713910
s3-client-1, 3362, 4706800, 40.5235, 642.199097, 7.192629
s3-client-1, 3819, 5346600, 35.5280, 723.181763, 8.099636
s3-client-1, 3402, 4762800, 45.5507, 617.739929, 6.918687
s3-client-1, 3547, 4965800, 40.5099, 695.567200, 7.790353
s3-client-1, 3138, 4393200, 50.5006, 626.777039, 7.019903
s3-client-1, 3891, 5447400, 45.5239, 742.641846, 8.317589
s3-client-1, 3886, 5440400, 55.5215, 745.032532, 8.344364
s3-client-1, 3550, 4970000, 50.5586, 635.496765, 7.117564
s3-client-1, 3449, 4828600, 60.5307, 649.788147, 7.277627
22852(1450946364)#traffic-generator (INFO): >>>> s3-client-1, 40422 SDUs, 56590800 bytes in 60307 ms, 7.507029 Mb/s
s3-client-1, 3688, 5163200, 55.5236, 704.274841, 7.887878
22852(1450946370)#traffic-generator (INFO): Flow torn down remotely [port-id = 3]
22852(1450946370)#traffic-generator (INFO): Flow torn down remotely [port-id = 4]
s3-client-1, 3763, 5268200, 60.5345, 703.958557, 7.884336
22852(1450946370)#traffic-generator (INFO): >>>> s3-client-1, 43920 SDUs, 61488000 bytes in 60345 ms, 8.151529 Mb/s
```

Log of the ipcm on the server:
```
20518(1450946304)#ipcm.flow-alloc (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between s1-server:1:: and s3-client:1::
20518(1450946304)#ipcm.flow-alloc (INFO)[allocate_flow_response_event_handler]: : Informing IPC process s1.dc:1:: about flow allocation from application s1-server:1:: to application s3-client:1:: in DIF dc::: [success = 1, port-id = 3]
20518(1450946310)#ipcm.flow-alloc (INFO)[flow_allocation_requested_remote]: Arrived request for flow allocation between s1-server:1:: and s3-client:1::
20518(1450946310)#ipcm.flow-alloc (INFO)[allocate_flow_response_event_handler]: : Informing IPC process s1.dc:1:: about flow allocation from application s1-server:1:: to application s3-client:1:: in DIF dc::: [success = 1, port-id = 4]
```

Log of the ipcm on the client:
```
18954(1450946304)#ipcm.flow-alloc (INFO)[flow_allocation_requested_local]: IPC process s3.dc:1:: requested to allocate flow between s3-client:1:: and s1-server:1::
18954(1450946304)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Informing IPC process s3.dc:1:: about flow allocation from application s3-client:1:: to application s1-server:1:: in DIF dc::: [success = 1, port-id = 3]
18954(1450946304)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Applications s3-client:1:: and s1-server:1:: informed about flow allocation result
18954(1450946310)#ipcm.flow-alloc (INFO)[flow_allocation_requested_local]: IPC process s3.dc:1:: requested to allocate flow between s3-client:1:: and s1-server:1::
18954(1450946310)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Informing IPC process s3.dc:1:: about flow allocation from application s3-client:1:: to application s1-server:1:: in DIF dc::: [success = 1, port-id = 4]
18954(1450946310)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Applications s3-client:1:: and s1-server:1:: informed about flow allocation result
```

On even more concurrent flows it happens the follow:
```
terminate called after throwing an instance of 'rina::FlowNotAllocatedException'
  what():  Invalid operation invoked when the flow is not allocated
Aborted
```

**Comment by edugrasa** [comment] 2016-02-11 09:15
Closing, duplicate of #388

**Closed by edugrasa** 2016-02-11 09:15 UTC
