### ISSUE TITLE
Pristine-1.3: Misbehavior during flow deallocation

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#779] opened 2015-10-28 09:01 UTC
**Where:**
This happens to me while using Pristine-1.3 branch.

**What:**
When I run multiple client with the same name on the same node, and for target the same server (don't ask me why), then different flows are correctly allocated to that server. If one of this client terminate it's job in advance, all the flows to that server are deallocated simultaneously (probably because they have the same name).

**How:**
Launching 2 client with the same name, destination the same server instance, should be enough to reproduce this misbehavior.

**Why:**
I said don't ask!!

**Comment by edugrasa** [comment] 2016-02-11 09:13
Closing, duplicate of #388

**Closed by edugrasa** 2016-02-11 09:13 UTC
