### ISSUE TITLE
ipcm: shim-tcp-udp is not properly destroyed on exit

### ISSUE THREAD

**Issue by dstaesse** [IRATI/stack#754] opened 2015-09-23 20:10 UTC
first time starting the ipc manager, registering a normal IPCP with the shim works:
```
3790(1443038501)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process test1.IRATI:1:: at DIF shim.DIF::: through IPC process test-tcp-udp:1::

3790(1443038501)#ipcm.ipcp (INFO)[ipcm_register_response_ipcp]: IPC process test1.IRATI:1:: informed about its registration to N-1 DIF shim.DIF:::

3795(1443038501)#ipcp[2].resource-allocator (INFO): IPC Process registered to N-1 DIF shim.DIF
3795(1443038501)#librina.rib (INFO): Object with name /daf/irm/difregistrations/shim.DIF, class DIF registration, instance 16 added to the RIB
```
after Ctrl-C in the IPCPs are reported to be destroyed:
```
^C3790(1443038633)#ipcm (INFO)[destroy_ipcp]: IPC process destroyed [id = 1]

3790(1443038633)#ipcm (INFO)[destroy_ipcp]: IPC process destroyed [id = 2]
```
however, after restarting the ipcm, registration with the shim fails:
```
4479(1443038662)#ipcm (INFO)[register_at_dif]: Requested DIF registration of IPC process test1.IRATI:1:: at DIF shim.DIF::: through IPC process test-tcp-udp:1::

4479(1443038662)#ipcm.ipcp (ERR)[ipcm_register_response_ipcp]: Cannot register IPC process test1.IRATI:1:: to DIF shim.DIF:::

4479(1443038662)#ipcm (ERR)[apply_configuration]: Problems registering IPCP 2 to DIF shim.DIF
```
there are remainders of the shim IPCP in the system:
```
dstaesse@m:/usr/local/irati/bin$ ps ax | grep shim
 3757 ?        S<     0:00 [shim-tcp-udp-rw]
 3758 ?        S<     0:00 [shim-tcp-udp-ww]
 3820 pts/0    S+     0:00 grep shim
```

**Comment by edugrasa** [comment] 2016-02-11 16:07
The processes you report (work queues) are created when the shim-tcp-udp is modprobed and destroyed when the shim-tcp-udp kernel module is unloaded (they are not related to creation/destruction of shim IPCPs). 

The issue is that the shim doesn't clean the flows and application registrations when it is destroyed, duplicate of #575, closing

**Closed by edugrasa** 2016-02-11 16:07 UTC
Labels: bug
