### ISSUE TITLE
pristine-1.5:  Kernel dump when shutting down IPCM (with mad)

### ISSUE THREAD

**Issue by mcrotty** [IRATI/stack#966] opened 2016-06-21 08:47 UTC
IPCM console (with DEBUG)
------
^C1295(1466498498)#ipcp[2] (CRIT): Got signal 2
1290(1466498498)#ipcm (DBG): Stopping I/O loop...
1290(1466498498)#ipcm (DBG): Cleaning the house...
1290(1466498498)#ipcm.mad (DBG): IPCP 'test-eth-vlan'(1) is about to be destroyed...
1290(1466498498)#rib (DBG): Removing object over RIB(0x12ca780) instance id: '21' fqn: '/computingSystemID=1/processingSystemID=1/kernelApplicationProcess/osApplicationProcess/ipcProcesses/ipcProcessID=1'
1290(1466498498)#rib (DBG): Object '/computingSystemID=1/processingSystemID=1/kernelApplicationProcess/osApplicationProcess/ipcProcesses/ipcProcessID=1' of class 'IPCProcess' succesfully removed (id:'21')
1290(1466498498)#librina.syscalls (DBG): Invoking SYS_destroyIPCProcess (324)

dmesg output
---------

[  304.355828] rina-ipcp-utils(DBG): Name at ffff880037b5eac0 finalized successfully
[  304.355830] rina-ipcp-utils(DBG): Name at ffff880037b5eac0 destroyed successfully
[  304.355855] ------------[ cut here ]------------
[  304.356076] kernel BUG at net/rina/ipcps/shim-eth-vlan-core.c:196!
[  304.356204] invalid opcode: 0000 [#1] SMP 
[  304.356880] Modules linked in: normal_ipcp(E) rina_default_plugin(E) shim_eth_vlan(E) rinarp(E) arp826(E) 8021q(E) garp(E) stp(E) mrp(E) llc(E) ppdev(E) serio_raw(E) parport_pc(E) lp(E) parport(E) psmouse(E) ahci(E) libahci(E)
[  304.357243] CPU: 0 PID: 1290 Comm: ipcm Tainted: G            E   4.1.24-150-rina #29
[  304.357383] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[  304.357524] task: ffff88003dacb220 ti: ffff88003dae8000 task.ti: ffff88003dae8000
[  304.357661] RIP: 0010:[<ffffffffa0096b23>]  [<ffffffffa0096b23>] inst_data_mapping_get+0x73/0x80 [shim_eth_vlan]
[  304.357817] RSP: 0018:ffff88003daebeb8  EFLAGS: 00010246
[  304.357894] RAX: 0000000080408001 RBX: ffff880037dda000 RCX: 0000000180400017
[  304.357979] RDX: 0000000000000040 RSI: ffffea0000f47fc0 RDI: 0000000000000000
[  304.358064] RBP: ffff88003daebec8 R08: ffff88003d1ff640 R09: 0000000180400016
[  304.358149] R10: ffffea0000f47fc0 R11: ffffffff8176c723 R12: 0000000000000000
[  304.358234] R13: ffff880037d92180 R14: ffff880037dda060 R15: 00007fff069a7b58
[  304.358320] FS:  00007fa257fa3780(0000) GS:ffff88003fc00000(0000) knlGS:0000000000000000
[  304.358365] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[  304.358365] CR2: 000000000205a008 CR3: 0000000037fc1000 CR4: 00000000000006f0
[  304.358365] Stack:
[  304.358365]  ffff880037dda000 ffff880037dda060 ffff88003daebef8 ffffffffa0096cce
[  304.358365]  ffff880037ab02a0 ffff880037ab02a8 0000000000000001 00000000012b5720
[  304.358365]  ffff88003daebf28 ffffffff8178ad93 0000000000000001 0000000000000001
[  304.358365] Call Trace:
[  304.358365]  [<ffffffffa0096cce>] eth_vlan_destroy+0x19e/0x280 [shim_eth_vlan]
[  304.358365]  [<ffffffff8178ad93>] kipcm_ipc_destroy+0x73/0x110
[  304.358365]  [<ffffffff8178fa64>] SyS_ipc_destroy+0x54/0x60
[  304.358365]  [<ffffffff817a87b2>] system_call_fastpath+0x16/0x75
[  304.358365] Code: 75 ee 48 c7 c7 80 d6 09 a0 e8 0a 19 71 e1 48 89 d8 5b 41 5c 5d c3 66 90 48 c7 c7 80 d6 09 a0 e8 f4 18 71 e1 5b 41 5c 31 c0 5d c3 <0f> 0b 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 48 85 
[  304.358365] RIP  [<ffffffffa0096b23>] inst_data_mapping_get+0x73/0x80 [shim_eth_vlan]
[  304.358365]  RSP <ffff88003daebeb8>
[  304.372743] ---[ end trace 442d84db340afd9f ]---

**Comment by edugrasa** [comment] 2016-06-29 15:34
Closing, it is a duplicate of #925

**Closed by edugrasa** 2016-06-29 15:34 UTC
Labels: duplicate
